### ISSUE TITLE
Rendering Context 2D | SpringRoll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#10]
Is there any class which helps to render 2d context to canvas in the springroll? 

Example : 

    stage.update();    
    var ctx = stage.canvas.getContext("2d"); //How to achieve 2d context in springroll?
    ctx.save();
    ctx.rotate(Math.random() * Math.PI);
    ctx.drawImage(bmp1.image, Math.random()*200, Math.random()*200);

**Comment by bigtimebuddy** [comment]
If you want to use context2d directly, there's a class called `springroll.NativeDisplay` which is analogous to PixiDisplay or EaselJSDisplay.

Create a canvas element to render your context2d display.
```html
<canvas id="native" width="900" height="500"></canvas>
```

Create the application display. This will set the native display as the main display.

```js
// Create an application
var app = new springroll.Application({
	canvasId: "native",
	display: springroll.NativeDisplay
});

app.once('init', function()
{
	var ctx = this.display.stage;
	ctx.save();
	ctx.rotate(Math.random() * Math.PI);
	ctx.drawImage(bmp1.image, Math.random()*200, Math.random()*200);
});
```

If you don't want the NativeDisplay to be your main display, you can add it after the application has been created:

```js
var display = app.addDisplay('native', springroll.NativeDisplay);
var ctx = display.stage;
ctx.save();
ctx.rotate(Math.random() * Math.PI);
ctx.drawImage(bmp1.image, Math.random()*200, Math.random()*200);
```

**Comment by praveen4565** [comment]
Thanks @bigtimebuddy . I am trying to add native display in game state
Example: 
p.enterDone=function(){
 this.display = this.app.addDisplay('native', springroll.NativeDisplay);
  this.ctx = display.stage;
}

throwing error : Uncaught TypeError: Cannot read property 'NativeDisplay' of undefined

Am i doing it right way?

**Comment by bigtimebuddy** [comment]
You need to make sure that that Native Display module is included in your *springroll.json* libraries. For example, `"components/springroll/dist/modules/native-display.js"`

**Comment by praveen4565** [comment]
I have added the reference. Now I am getting the error as :

Uncaught Display exists with id 'stage'

**Comment by bigtimebuddy** [comment]
Couple of things:
* `<canvas>` elements that have unique IDs throw that error. Make sure you're not using "stage" for both canvases.  
* The `app.display` is the "main" display (the one added first), this might not be the display you want if you are managing multiple displays. Use `app.getDisplay(id)`
* `display.canvas.getContext('2d')` is equivalent to `display.stage` (using NativeDisplay)
