### ISSUE TITLE
Audio not working in IE11 - "Unable to initialize SoundJS with a plugin!"

### ISSUE THREAD

**Issue by trjh2k2** [SpringRoll/SpringRoll#101]
I'm currently not getting any audio in IE11, and the console gives the error "Unable to initialize SoundJS with a plugin!".  My understanding is that IE is supposed to use flash as a fallback for audio, but if I break in Sound.init() in sound.js and call isSupported() on the FlashAudioPlugin (or the WebAudioPlugin), it returns false.  However, if I add the HTMLAudioPlugin to the defaultOptions.plugins list, that plugin appears to be working.

**Comment by andrewstart** [comment]
Flash is installed and enabled, right? I generally only had problems like
that when I forgot to install Flash on a new VM of Windows.

**Comment by trjh2k2** [comment]
Turns out we thought Flash was installed for IE, but it was not.
