### ISSUE TITLE
Springroll isn't compatible with the latest version of node or npm

### ISSUE THREAD

**Issue by yanshcherbakovatredspace** [SpringRoll/SpringRoll#105]
When using node version 5 up and npm 3 up, when running npm install, npm throws many warnings and errors. Seems that a lot of modules are deprecated and need to be updated.

Springroll needs to be adjusted to be compatible with the latest version of node and npm.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
