### ISSUE TITLE
Including Sound JS prevents app.load callbacks from firing

### ISSUE THREAD

**Issue by mebrelsford** [SpringRoll/SpringRoll#109]
Normally, this would result in logging the loaded object:

```
app.load("assets/content/slack-imgs.webm", function(result){
    console.log("loaded", result);
});
```

However, simply by including SoundJS v0.62, or the Springroll fork of SoundJS, the callback function no longer fires. It still seems to attempt to load the file, however, since if I provide an invalid url, I'll see 404 errors.

**Comment by mebrelsford** [comment]
I'm also happy to hear of any workarounds that will allow me to load audio at runtime (not during preload) and then play it once it's loaded.

**Comment by mebrelsford** [comment]
Looks like if I add this line:

    createjs.Sound.alternateExtensions = ["mp3", "ogg"];

The loaded events start firing again. However, if I try to then load a .webm, it ignores the file extension and attempts to load that file, but with a .mp3 file extension.

In other words, this:

                this.load(
                    {
                       id: "thing",
                       src: "assets/content/slack-imgs.webm",
                       type: createjs.AbstractLoader.VIDEO

                    },
                    
                    function(result){
                        console.log("result: ", result);
                    }
                    
                );

Results in this:

preloadjs.min.js:12 GET [...omitted...]/development/assets/content/**slack-imgs.mp3** 404 (Not Found)

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
