### ISSUE TITLE
Receiving 404 not found error for index.html of build in SpringrollConnect

### ISSUE THREAD

**Issue by simrisek-sinkingship** [SpringRoll/SpringRoll#11]
I've put up a build of odd-squad-dr-o; it works locally and I can see in Jenkins that the index.html is there in the Workspace, but when I try to play the development build, I get the following:
![firebug](https://cloud.githubusercontent.com/assets/13528670/8919098/c30e83b4-348a-11e5-8b04-644c1e694a64.jpg)
Any suggestions?

**Comment by bigtimebuddy** [comment]
Fixed. Try again.
