### ISSUE TITLE
Question: Chrome 52 audio issue?

### ISSUE THREAD

**Issue by thebarge** [SpringRoll/SpringRoll#113]
Hi-
Are you seeing this issue in SpringRoll?
https://bugs.chromium.org/p/chromium/issues/detail?id=634444
We're currently experiencing this issue with our project, which isn't SpringRoll, but shares some similarities (CreateJS, WebAudio). Wanted to verify if this is an issue with SR as well. Thanks! (Sorry if there was a non-GH issue way to ask this, wasn't sure of the protocol.)

**Comment by yanshcherbakovatredspace** [comment]
I've seen this happen intermittently where if the game is paused for a while. The audio doesn't come back. I need to look through my notes, as I think we had a solution for this. I will get back to you on this.

**Comment by thebarge** [comment]
Just to close the loop and leave this here for future reference, we tracked this down to an interaction between Howler.js (which we were using to process audio) and Chrome 52. There's a Howler defect here: https://github.com/goldfire/howler.js/issues/593 but we have a workaround that works at this point.

**Comment by yanshcherbakovatredspace** [comment]
The issue I experienced is quite intermittent and difficult to reproduce. Closing for now but will keep as a reference as the interaction in howler may be a good reference in the future.
