### ISSUE TITLE
To enable the tool box which beside in the top right corner of preview page in springroll studio

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#114]
We get an options in top right corner(ToolBox) of preview in springroll studio to pause, play etc..
which is not appearing, when we browse the url in the browser.  
Is there any option to enable the toolbox as like preview page in the browser of hosted game with the absence of springroll environment??

**Comment by yanshcherbakovatredspace** [comment]
Springroll Studio provides a basic container for the game to test the play, pause and captions buttons. Those buttons are hooked through Springroll container, and therefore not available when you run the game straight in the browser.

For those buttons to be available, you need to create them as DOM elements. For example you'd have `<button id="playButton">Play</button>` which is on the containing page for the game, that is running the Springroll Container, and then you would hook the play buttons to those DOM elements.

Please refer to the Springroll Container documentation:

https://github.com/SpringRoll/SpringRollContainer/blob/master/README.md
https://github.com/SpringRoll/SpringRoll/wiki/Container-Client-Module

The Springroll Container Read me documentation explains how this can be done.

Here is an example of a basic Springroll container html file.

```
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="assets/css/container.min.css">
    <script src="assets/js/container.js"></script>
  </head>
  <body>
    <div class="appWrapper">
      <iframe id="appContainer" src="game.html" frameborder="0" scrolling="no"></iframe>
      <script>
        var container = new springroll.Container("#appContainer");
        container.openPath("game.html");
      </script>
    </div>
  </body>
</html>
```

Where container.min.css contains your styling for the containing page, and container.js contains the libraries that are necessary to run the Springroll Container:

- jQuery
- bind-polyfill
- Bellhop
- SpringrollContainer library

**Comment by yanshcherbakovatredspace** [comment]
Answered.
