### ISSUE TITLE
offline Game and Security

### ISSUE THREAD

**Issue by manjunath801** [SpringRoll/SpringRoll#115]
Hi, Using SpringRoll framework can the game be played offline on browser, Any feature which can be used to achieve this and Is there way to secure(any kind of security implementation) the assets/content using Springroll?

Manjunath T

**Comment by yanshcherbakovatredspace** [comment]
Any game built with Springroll can be played offline in the browser as long as all the files and assets are local. However, they need to be running through some sort of file server (web server) locally in order for preloading to work. It won't work through `file://`.

SpringrollStudio facilitates this for the purpose of local development, but if you needed for the game to run locally offline, you will need to build something similar that runs the game through a file server.

**Comment by yanshcherbakovatredspace** [comment]
@manjunath801 Following up on your inquiry. Do you require further information on your inquiry?

**Comment by yanshcherbakovatredspace** [comment]
Closing this issue.

**Comment by manjunath801** [comment]
Hi, Sorry for coming back late. If we use Springroll Studio to play the content locally, how can we secure the assets? Is there a way to encrypt the package and Decrypt while playing?

**Comment by yanshcherbakovatredspace** [comment]
@manjunath801 Can you describe your use case for me? For what reason do you want to secure the assets with encryption?

**Comment by manjunath801** [comment]
We are developing an Learning HTML5 application in which there are many images and audio files. When user downloads the app locally to play offline, these assets should be made protective avoiding user to see or hear the images and audio files 

I hope its clear?

**Comment by yanshcherbakovatredspace** [comment]
You mean to avoid seeing or hearing the images and audio files if attempting to view outside of the app? As in opening the images in an image program and opening the audio in an audio player? Essentially you don't want the user to be able to access the assets unless it is through the application correct?

**Comment by yanshcherbakovatredspace** [comment]
Springroll currently doesn't include any way to decrypt/encrypt assets through the web. All assets are passed to preloadJS that also has no cryptography feature so to be able to achieve what you're looking for is to create a layer in between when the assets are preloaded to decrypt the assets.

The only way I can think of this being done, is if you create a native container that includes the ability to do the necessary decryption upon opening the application. So your assets would be encrypted in the application package and would be decrypted by your application upon start. Then you can use Springroll normally within the application.

If you want to create applications using front end code, you may use something like http://nwjs.io or even React Native to create your containing applications.

Then achieve what you're looking for by using public-key cryptography which you use for encryption and decryption.

So once your application loads, you may decrypt the assets using public-key cryptography and then play the game in a WebView as normal.

If you plan to use nw.js, the following might be relevant to you:

https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot
https://github.com/nwjs/nw.js/issues/269

**Comment by manjunath801** [comment]
Thank you :)

**Comment by yanshcherbakovatredspace** [comment]
My pleasure!

Closing this issue, if you have any additional questions feel free to continue to comment in this issue to re-open it.
