### ISSUE TITLE
Desired way of muting SR app

### ISSUE THREAD

**Issue by Jacob-Geb** [SpringRoll/SpringRoll#12]
What is the preferred way of getting/setting the master muted state for the SR sound class (and the application in general)?

Temporarily I've added the following hack to the sound module..
``` 
p.setMute = function(muted) {
	SoundJS.setMute(muted);
};

p.getMute = function() {
	return SoundJS.getMute();
};
```

**Comment by andrewstart** [comment]
Sound has a muteAll property, just set that to true or false. It also just uses SoundJS.setMute(). Currently it is write-only, although we should probably change that.
Additionally, you could use setContextMute() to set the mute status of specific sound contexts, if you have your audio divided into contexts like SFX, VO, and music.
