### ISSUE TITLE
"Music" property plays double if original clip doesn't load before property change.

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#122]
We noticed that in one of our games the background audio plays double in certain cases. If, for example, we have a music track that plays on the game's intro menu, and the player immediately taps "play game" _before_ the background music has loaded and begins playback, when the game starts (setting `app.music` to another track) this new background music track loads and plays simultaneously with the game menu's background track that finally loaded.

Strangely, the menu background track continues to loop for the rest of the game, along with whatever background audio should be playing. So if the player finishes the game and returns to the menu, there will be two menu background tracks playing.

This doesn't occur if the player loads the game and waits to press "play game" (and thus delaying the `app.music` property change) until the menu background music has started playback.

**Comment by andrewstart** [comment]
I suspect that https://github.com/SpringRoll/SpringRoll/pull/123 would fix this issue, but it would be great if you could test it for me.
