### ISSUE TITLE
Forked EaselJS

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/SpringRoll#125]
I noticed that SpringRoll has its own forked EaselJS, but I would like to know if there is a way I could use my own forked EaselJS? How can I get it running? Are there any specific file(s) or method, etc needed to get it running?

I'm asking because I am just trying to use my own forked EaselJS (fairly newer version, which includes the MovieClip.js), and nothing is showing up. (sound and objects are there, checking through the console, but just a white screen)

Thanks for your help!

**Comment by yanshcherbakovatredspace** [comment]
Hi @gregmax17 You can set `bower.json` to point to your fork instead of Springroll fork like so:

```
"dependencies": {
		"normalize-less": "*",
		"springroll": "0.4",
		"bellhop": "*",
		"soundjs": "https://github.com/SpringRoll/SoundJS.git",
		"easeljs": "https://github.com/gregmax17/EaselJS",
		"tweenjs": "https://github.com/SpringRoll/TweenJS.git"
	}
```

**Comment by yanshcherbakovatredspace** [comment]
Another thing to note is that the Springroll fork has specific modifications, for your fork to work properly with Springroll, make sure to merge the Springroll fork changes into yours.

In the short future, we will be merging back into the main repo, however if you want to use your fork in the interm, make sure you merge the Springroll changes into your fork.

The Springroll changes are specified in the README.md file at the bottom.

**Comment by yanshcherbakovatredspace** [comment]
The following changes were made to the Springroll fork of EaselJS:

## SpringRoll specific changes
* Version numbers have been removed from built files.
* DisplayObjects have a hitShape property, which overrides hitArea/default hit testing with the geometric shape that hitShape is set to.
* Bitmap doesn't attempt to draw sourceRects with a width or height of 0 (or less).
* Container.removeAllChildren() is optionally recursive, pass true as a parameter.
* Time based MovieClips have been redone. Now they track an elapsed time which counts from the start of their timeline. This allows for greater control over playback, including strict syncing to audio.
* Text allows for drawing stroked text. An graphical issue with custom fonts has also been fixed.
* ColorFilter now attempts to account for browsers that don't handle pixel manipulation properly.
* Rectangle.contains() allows for a Point or Rectangle to be passed for the first parameter.
* Touch no longer breaks when Touch.disable() is called on a stage that did not have touch in the first place.
* Containers that are not tickEnabled still pass ticks on to their children if tickChildren is true.
* Changed how MovieClips fetch the framerate from parents to properly set the new _duration as well.
* Added a way to disable mouse events except mousemove on the stage.

**Comment by gregmax17** [comment]
I see... 

Thank you for the quick response.

Another reason I wanted to use my own forked version of EaselJS was because it has the SpriteContainer (an the EaselJS version appears to be old?). 

I would like use a WebGL filter effect, but I can't seem to get PIXI and EaselJS working with SpringRoll, or just PIXI alone. Seems to always error out on me, even a plain vanilla build.

Do you know how I can get PIXI working with EaselJS? Or a way to get the SpriteContainer working?

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
