### ISSUE TITLE
Sounds with Spring Roll

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/SpringRoll#129]
I'm trying to port a game to Spring Roll, and I'm having difficulties with the Sound.

- Can I use sound Sprites? Example?
- Must everything be in a config upfront, can't my sounds be dynamic? For example...
- How do I get dynamic VO and Captions to work with this? (ie, "you scored", "40", "2", "points")

**Comment by probityrules** [comment]
As far as I'm aware, Springroll doesn't support sound sprites, but they aren't quite as necessary now that iOS has better audio support.

If you put your sounds in the config, you can still dynamically reference them on use with [app.voPlayer](http://springroll.io/SpringRoll/docs/classes/springroll.VOPlayer.html#method_play). For example:
```
    var number = "number-" + ((Math.random() * 10) >> 0);

    app.voPlayer.play(["you-scored", number, "points"])
```
Where "you-scored", "points", and "number-0" through "number-9" are individual audio ids in your upfront vo config:
```
{
    "context": "vo",
    "path": "assets/audio/",
    "sounds": ["you-scored", "points", "number-0", "number-1", "number-2", "number-3", "number-4", "number-5", "number-6", "number-7", "number-8", "number-9"]
}
```

I'm also curious about captions for this sort of audio concatenation. I've dealt with it in the past by captioning each individual audio clip, but then there are multiple tiny captions that aren't easily readable compared to, say, a single caption "You scored 42 points!"

**Comment by gregmax17** [comment]
I still lean towards sound sprites, even with the improved audio support. I like to load one file, not dozens upon dozens.

Captions needs to be reworked in order to support dynamic vo/text.

In the Spring Roll Connect, when previewing a game, in the top right hand corner there are buttons like audio, pause/resume, cc, etc. When I click on the audio drop down how come it doesn't show the toggle buttons for music and vo? Any events that tell me the admin clicked on those buttons?

<rant>
I feel like this spring roll needs to be behave more like an api, not a wrapper.
</rant>

**Comment by andrewstart** [comment]
The container should show buttons for toggling music, sfx, and vo if the initial config for the application sets up [sound contexts with the names `music`, `sfx`, and `vo` respectively](https://github.com/SpringRoll/SpringRoll/blob/master/src/container-client/ContainerClientPlugin.js#L127).

Concatenating captions for dynamically combined VO is something that I have done in the VOPlayer's AS3 predecessor, but it's a little awkward when you want to combine dynamic and non-dynamic VO with one go ("you scored", "42", "points!", "Great, now let's shoot for an even bigger number next time").
If I were to do it again, I'd probably create some sort of dynamic caption generator singleton that is an interface between the VOPlayer and the Sound/Caption singletons. Then you'd do something like
```javascript
myVOPlayer.play([DynamicSoundMaker.combine(['you-scored', 'number-10', 'points!']), 'good-job'], myOnComplete);
```
Does that API seem like a good solution to that problem?

**Comment by yanshcherbakovatredspace** [comment]
@gregmax17 Has the above comment solved your issue with audio?

**Comment by chipbell4** [comment]
Also, I'd advise against audio sprites in Android. Audio decoding is still pretty bad in Android, and a larger audio file will essentially steal the UI thread during decoding. If the file's too large, it'll cause the UI thread to hang for too long, Android to then think the app is frozen, and then force close everything. In general, decode time is _actually longer than download time_ for most audio on Android.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
