### ISSUE TITLE
Debug option in Springroll Studio

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#13]
Wanted to know better way of debugging while working on Springroll projects.

I have tried by using debug option which is in "Tasks" option.But not able to debug line by line. Even If we try to use debugger in the script, throwing error while building project.

**Comment by theBarge** [comment]
When working in active development, we often use the `grunt dev` option which continually builds the libraries and main when changes are detected. In terms of errors being thrown, an example of the error (screenshot or stack trace as appropriate) would be helpful to diagnose the issues you are having.

**Comment by praveen4565** [comment]
If i use debugger in the code i am getting below error.

  179 |        debugger;
                 ^ Forgotten 'debugger' statement?
>> 1 error in 12 files
Warning: Task "jshint:main" failed. Use --force to continue.

Aborted due to warnings.

**Comment by theBarge** [comment]
Please refer to https://jslinterrors.com/all-debugger-statements-should-be-removed

**Comment by praveen4565** [comment]
Thanks @theBarge , How can we debug line by line of original source file rather minified ? 

For instance :Assume I have GameState js. If I want to debug js line by line by putting breakpoint? How can I do this?

**Comment by theBarge** [comment]
When building in debug mode (as in when running `grunt dev`, `grunt debug`, or similar) source is not minified. I'm not personally familiar with inserting `debugger;` into our javascript as that is not a part of our workflow here, but we often add breakpoints using the Developer Tools and are brought to the correct line when that breakpoint is hit. Yes, when minified, it's hard (impossible? :smile: ) to debug line by line.

**Comment by bigtimebuddy** [comment]
There are two options for using debugger. 

First, have jshint ignore the debugger statement:

```js
debugger; // jshint ignore:line
```

Second, add this directive anywhere in your code to disable warnings for debugger (more information [here](https://jslinterrors.com/all-debugger-statements-should-be-removed)):

```js
/*jshint -W087 */
```

Also, I would encourage you to use a `DEBUG` compile constant so debugger breakpoints don't get added to the release build:

```js
if (DEBUG) debugger;
```
