### ISSUE TITLE
Right/bottom alignment broken in ScaleItem?

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#132]
(escalating this to its own issue - edit: this is in ScaleItem.js, not ScaleManager.js)

I can't seem to get right and bottom alignment working properly. 

It seems as if in the libraries there's an "origMarginHori" property that is used to signify the initial horizontal position of a ScaleItem. In the ALIGN_RIGHT switch case, this origMarginHori value gets set as the value of the full display width, suggesting that it's an offset from the left side. But then in the resize() method, that value (scaled) is subtracted from the display width. This results in the ScaleItem being moved far away from the right edge. My expectation was that the x value for a right-aligned object would be its offset from the right side - in other words, if the origMarginHori needs to be subtracted from the right edge on resize, then that value should be zero by default (if I change the code so that origMarginHori is set to 0, it behaves as I expect).

Similar issue with ALIGN_BOTTOM.

**Comment by andrewstart** [comment]
The expectation of the UI layout code is that you set up your UI the way you want it to be positioned in the title safe size, and then add rules for repositioning/scaling when the stage size is changed. As such, `x` and `y` are not margins, but location at title safe dimensions.

**Comment by gbhkit** [comment]
OK thanks, I think I understand now.
