### ISSUE TITLE
Pixi.js states and panels?

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#133]
I see classes for BasePanel and BaseState that use Easel.js (in easels-states.js), but I can't find similar for Pixi.js. Is there such?

**Comment by andrewstart** [comment]
There is not - they were created because we had made and were making a number of EaselJS games that were set up basically the same, but the PixiJS games were created with more varied needs. The stuff in easeljs-states module don't do anything that is particularly special anyway.

**Comment by gbhkit** [comment]
Ah, cool; glad I wasn't just overlooking something. Mainly I was searching for a straightforward way to be hooked into the same asset loading and scaling flow using Pixi as the renderer.

**Comment by andrewstart** [comment]
Yep, that stuff is built into the regular BaseState with the `preload` and `scaling` state options.
