### ISSUE TITLE
[Pixi4 update] Support for features moved from our fork to Pixi

### ISSUE THREAD

**Issue by andrewstart** [SpringRoll/SpringRoll#134]
A few features have been added to Pixi from our fork, and some of them are important to code within Springroll:
* [Global interaction events](https://github.com/pixijs/pixi.js/pull/2658)
* [Custom cursor handling](https://github.com/pixijs/pixi.js/pull/3331)
* [Ability to use asset parsers with outside loaders](https://github.com/pixijs/pixi.js/pull/3676)
* InteractionData has an `identifier` property - we called it `id`

Additionally, pointer events have been added, and are emitted along with native mouse/touch events. As such, we could consider changing to use those instead of mouse/touch events for Buttons/dragging. This would require desktop/mobile testing, but should provide better future proofing and possibly more responsiveness if mouse/touch events are sent on a delay after pointer events (like the way touch->mouse events work).

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
