### ISSUE TITLE
[Pixi4 update] Support for legacy projects to make this change slightly less breaking

### ISSUE THREAD

**Issue by andrewstart** [SpringRoll/SpringRoll#135]
We should add an option to mixin deprecations for features within our fork of Pixi 3 that have been added to Pixi 4 under a different name:
* [Global interaction events](https://github.com/pixijs/pixi.js/pull/2658)
* [Custom cursor handling](https://github.com/pixijs/pixi.js/pull/3331)
* InteractionData has an `identifier` property - we called it `id`

These would be enabled with a `legacyPixi` option or the like, but probably would not be enabled by default (which does make it a little breaking).

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
