### ISSUE TITLE
[Pixi4 update] Support for features still in our fork, provided as mixins or otherwise living in our library

### ISSUE THREAD

**Issue by andrewstart** [SpringRoll/SpringRoll#136]
Our fork of Pixi 3 still contains some features that do not exist in Pixi 4:
* `PIXI.utils.useFilenamesForTextures`, a boolean to globally use filenames for texture ids instead of the full url. All Texture fetching respects this.
    * We could make a potentially breaking change by ignoring this setting and always adding Textures to the global caches by id/filename when loaded via Springroll (the behavior when `PIXI.utils.useFilenamesForTextures` was `true`), and just assuming that people won't care if they are loading Textures via Pixi instead. Things like `PIXI.Texture.fromFrame` or `PIXI.Texture.fromImage` will still work fine if Springroll adds a Texture via id and you try to fetch it via id.
* Destruction of a BaseTexture destroys all Textures in the texture dictionary that reference that BaseTexture.
    * We should be able to support this by mixing in a wrapper for BaseTexture.destroy.
* Look into 'width' and 'height' properties on Container being overrideable. Pixi is now written in ES6 and transpiled to ES5, so this may no longer be an issue. If it is, then we could see about making a PR to Pixi.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
