### ISSUE TITLE
Captions not displaying their full duration

### ISSUE THREAD

**Issue by kgieber** [SpringRoll/SpringRoll#139]
How does the captioning component work for end times? I put together captions for one of our games and noticed that the captions appear to be cleared as soon as the audio is done despite the duration I set in the caption.json file. There are times when I need the captions to be displayed longer than their audio, for example when a short-sounding word, such as 'ant' is spoken on its own. Is there a way to do this?

**Comment by andrewstart** [comment]
Currently there is not. Stopping the caption when the audio ends was a quick and easy safety measure, but we really should have the caption finish itself when it outlasts the audio.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
