### ISSUE TITLE
Running multiple animations concurrently 

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#14]
I have requirement where I need to play multiple objects animations (published from Flash as JS animation objects) at a time. This part has been achieved.

The query is :

Each of the objects has a click event which plays the respective animations. For ease of explaining, lets consider 2 objects A and B, on click of object A animation will start for that object. 
While this animation is playing if I click on object B the animation of object A will freeze and object B animation plays. But ideally both animations should be playing simultaneously.

I am using  “ this.game.media.playMovie();” to play animations.

Please could you suggest any options to resolve this issue.

**Comment by andrewstart** [comment]
this.game.media.playMovie() is intended for singular animations, like a character popping up to deliver some voice acting. If you need to play multiple animations at the same time, you should be using springroll.easeljs.Animator.play() directly.

**Comment by shruthims91** [comment]
Thanks @andrewstart . Yes, I have already tried with Animator.play() its playing,but animations are playing faster than actual speed and also its looping even though we have the frame labels.

**Comment by andrewstart** [comment]
That's interesting, since media.playMovie() is just a wrapper for Animator.play() with learning events attached..

**Comment by shruthims91** [comment]
Animator.play(object, {anim: "", audio: ""}, Oncomplete());  this I have used to play but  speed is more than actual. if I replace with media.playMovie() this works fine.

**Comment by andrewstart** [comment]
You could try setting object.framerate to the framerate that it was made at, just to make sure that that value is correct.

**Comment by shruthims91** [comment]
Thank you @andrewstart . Its working as expected.
