### ISSUE TITLE
Cross-domain issue with 'window.top.forceNativeAudio'

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#144]
I've just run into a breaking error with v1.0.2 and I think it's related to the new force native audio code. I get the following error when `window.top.forceNativeAudio` is checked:

> Uncaught DOMException: Blocked a frame with origin "http://springroll-tc.pbskids.org" from accessing a cross-origin frame.

I think it's breaking on this line, but this source shows it on "window.top.springroll", not directly on "window.top" like I'm seeing in my console: https://github.com/SpringRoll/SpringRoll/blob/master/dist/modules/sound.js#L647

**Comment by yanshcherbakovatredspace** [comment]
@probityrules This is a known issue, I have a patch for this coming shortly.

**Comment by yanshcherbakovatredspace** [comment]
@probityrules PR #143 Fixes this. Release is pending. You may point bower at `master` if need be.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
