### ISSUE TITLE
Async `app.userData.read` returns incorrect values.

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#148]
When using `app.userData.read()` from an <iframe> where the containing page uses a `springroll.Container`, the following code causes problems:

    app.userData.read('Key1', function (value1) {
        // expect value1 to be Key1's value
    });
    app.userData.read('Key2', function (value2) {
        // expect value2 to be Key2's value
    });

This works as expected when the app is not in an <iframe> but it seems that both callback functions are added to the first instance's request when SpringRoll uses a "userDataRead" event via bellhop.js. This happens:

    app.userData.read('Key1', function (value1) {
        // expect value1 to be Key1's value
        // Correct: value1 is Key1's value
    });
    app.userData.read('Key2', function (value2) {
        // expect value2 to be Key2's value
        // Incorrect: value2 is the same as value1 (Key1's value)
    });

I think I can get around this in the near term by making sure the first value is returned before reading another value so that the callbacks are attached to the correct event instance, or by storing all data on a single key, but this isn't ideal.

**Comment by andrewstart** [comment]
Yeah, the problem is that the `userDataRead` event (and `userDataWrite`) are not unique. I think that fixing this would need a major bump to Bellhop to add a uuid value to each `send()`, that responders are then required to give back in some form when telling Bellhop to send the response.

**Comment by bigtimebuddy** [comment]
Does this work if you call the `read` calls in series rather than parallel?

**Comment by probityrules** [comment]
Yes. As an interim fix for our current project, I created a working monkey-patch that avoids the problem by turning parallel calls into serial calls:

    app.userData.___read = app.userData.read;
    app.userData.read = (function () {
        var busy = false,
            callbackWrapper = function (callback, value) {
                var next = null;

                callback(value);

                if (queue.length) {
                    next = queue.shift();
                    app.userData.___read(next.key, callbackWrapper.bind(null, next.callback));
                } else {
                    busy = false;
                }
            },
            queue = [];

        return function (key, callback) {
            if (!busy) {
                busy = true;
                app.userData.___read(key, callbackWrapper.bind(null, callback));
            } else {
                queue.push({
                    key: key,
                    callback: callback
                });
            }
        };
    }());

**Comment by chipbell4** [comment]
_wipes off the cobwebs_: This should be resolved now I believe, since `UserData` now is Promise-based. Something like this:

```javascript
const value1 = await UserData.read('key1');
const value2 = await UserData.read('key2');
```

should prevent any collisions, since `await`-ing the promise should let the first one finish before the second one starts.

@probityrules Let me know though if you're still seeing an issue and we can investigate some more!
