### ISSUE TITLE
Using Spine for State Transition...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#151]
I may be missing something obvious here, but I can't seem to pinpoint the issue. We have a Spine set up with these four animations:
![image](https://user-images.githubusercontent.com/1324745/28718494-52953706-7374-11e7-9a83-e83ef45a5f75.png)

However, when we set `app.transition = new Spine();` using this Spine instance, we get the following error: `No valid animation label "onTransitionIn" in MovieClip [object Object]`

Do we need to go about this differently or is our Spine data set up incorrectly?

**Comment by andrewstart** [comment]
From what it looks like in one of my old projects - the last one I can remember using a Spine transition in - what you've got looks correct (but you shouldn't need the `_stop` animations). You have included the `pixi-spine` module from SpringRoll, right? What versions of things are you using? This project was set up for v3.0.8 of the SpringRoll fork of PIXI, and v0.4.8 of SpringRoll.

**Comment by probityrules** [comment]
I was missing `pixi-spine`. I had included the `animation` module but it didn't occur to me that I needed `pixi-spine` as well.

Oddly enough it's working *halfway* now: "onTransitionOut" is functioning correctly but "onTransitionIn" is not. I may be able to dig into this a bit now that it's partly there. We're using pixi v4.5.2 and SR v1.0.0.

**Comment by probityrules** [comment]
So, it works just fine. "onTransitionIn" just wasn't showing because the display was black and the transitional effect was black, with no loaded visual assets set to appear until post-transition.
