### ISSUE TITLE
Generated libraries.js file makes calls to undefined functions in Sound JS

### ISSUE THREAD

**Issue by Clement-E-Todd** [SpringRoll/SpringRoll#154]
Throughout the generated libraries.js file, there are several references to undefined "pause" and "resume" functions in SoundJS's WebAudioSoundInstance class. While this used to be the correct way to pause and resume sounds in SoundJS, the methods were deprecated and eventually removed from the library altogether. If we look at the SoundJS documentation, we can see that the correct way to pause and resume a sound is to set its "paused" property directly: http://createjs.com/docs/soundjs/classes/WebAudioSoundInstance.html

This issue results in voice-overs and music not pausing correctly when the game loses focus. This code works as a work-around for Springroll users until the issue is fixed:
`	// Patch audio errors in the generated Springroll libraries...
	createjs.WebAudioSoundInstance.prototype.pause = function() {
		this.paused = true;
	};
	createjs.WebAudioSoundInstance.prototype.resume = function() {
		this.paused = false;
	};`

**Comment by bigtimebuddy** [comment]
Currently, SpringRoll maintains a [fork](https://github.com/SpringRoll/SoundJS#changes-for-springroll) of SoundJS and will not work with the current main-line version.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
