### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by gpiffaretti** [SpringRoll/SpringRoll#155]
I'm using the example in the 'Usage' section. Installed springroll with bower.
I downloaded 'preloadjs.min.js' and included it as another dependency.

When I open my web page I keep getting:
Uncaught Unable to include 'createjs.Bitmap' in core.min.js:2

What am I doing wrong? Is there a complete and working example I can clone?

**Comment by gpiffaretti** [comment]
ok whatever, I downloaded the examples and will use that to kickstart the project. But it looks nothing like the basic usage example.

I think the following link was needed in my first attempt, but this wasn't mentioned as a dependency in the instructions:
<script src="../components/easeljs/lib/easeljs.combined.js"></script>

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
