### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by manjunath801** [SpringRoll/SpringRoll#157]
I am looking for an example on localization. How can we manage different language text and audio files?
Thanks

**Comment by chipbell4** [comment]
Hello,
The [`Languages`](https://github.com/SpringRoll/SpringRoll/blob/master/src/languages/Languages.js) module and plugin provide localization by substrings of URLs automatically during the load process. For instance:
```javascript
window.app.load('assets/sound/%LANG%/vo/help1.mp3');
```
will load "assets/sound/en/vo/help1.mp3", or "assets/sound/es/vo/help1.mp3" [depending on the value of `navigator.languages`](https://github.com/SpringRoll/SpringRoll/blob/master/src/languages/Languages.js#L151) or what is [set manually](https://github.com/SpringRoll/SpringRoll/blob/master/src/languages/Languages.js#L176) by calling `app.languages.setLanguage('es')`

Hope that helps!
