### ISSUE TITLE
GroupHint TypeError

### ISSUE THREAD

**Issue by kyfoote** [SpringRoll/SpringRoll#159]
When trying to use the Hints module, I've come across a TypeError when adding Group hints. This can be easily reproduced by calling:

```app.hints.group().vo("id");```

Group hints seem like they would be a very useful feature to use on games that have a lot of instructional scaffolding. When investigating, it appears it is a simple mis-match in property names. `tier` vs `_tier`. Where `_tier` is being created, but `tier` is being used.

The error happens on line 84 when using `vo()` but other hint types cause it also: 
```this.tier.push(new VOHint```

`this.tier` is undefined.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
