### ISSUE TITLE
Application's AssetManager doesn't properly unload assets loaded with SoundTask

### ISSUE THREAD

**Issue by cameronharvey92** [SpringRoll/SpringRoll#161]
Sounds can be preloaded in `Application.load()` via the SoundTask task if the provided asset config has an _id_ and a list of sound IDs (_sounds_). In `SoundTask.start()`, the loaded asset (array of sound IDs) has a destroy method appended to it to unload the audio files if called. However, when later calling `Application.unload()` or `Application.unloadAll()`, the underlying AssetCache's delete method misses this destroy() call because it handles the soundID array by attempting to destroy its members, _but not attempting to destroy the array itself_ if it contains a destroy method.

One solution could be to replace the following code in `AssetCache.delete()`:

```
else if (Array.isArray(result))
{
	result.forEach(destroyResult);
}
```

with the following code that safely checks and calls a destroy method on _result_ itself if it exists:

```
else if (Array.isArray(result))
{
	result.forEach(destroyResult);
	destroyResult(result);
}
```

**Comment by andrewstart** [comment]
Given that it is an array of strings with a `destroy()` method and the `forEach` is a waste of time to run, my preference would be to rearrange things to attempt calling `destroy()`, and if that didn't happen then check for arrays or plain objects. I'll whip up a PR tomorrow.
