### ISSUE TITLE
Whats the status of SpringRoll?

### ISSUE THREAD

**Issue by pieshop** [SpringRoll/SpringRoll#163]
Pull request #150 by @bigtimebuddy shows a substantial amount of work made in the 'next' branch attempting to modernise the framework. Any plans for this to go anywhere?

**Comment by chipbell4** [comment]
Great question! More than likely, we won't be merging Matt's PR as it stands. We're currently working on a 2.0.0 release but we do not have a branch pushed. In the meantime, I can at least give you an idea of where we see the framework going:

- Greater focus on accessibility, and providing tooling for making games more accessible with less work from devs (Captions, Text-to-speech, Color Blindness testing)
- Reduced focus on renderer and loader system, which should allow developers to use whatever rendering/loading/sound framework they want. However, we'll continue to provide examples on custom integrations
- Continued support for Iframe/Bellhop/Container communication layer
- Modern build process (ES6 modules, probably Rollup for bundling core, no more bower), along with an updated template.

A lot of this functionality is already ready in our local copies, and we should hopefully be pushing everything up shortly for others to peek at.

Also: If you come back and still haven't seen any action, feel free to ping me here and I'll keep you posted 👍 

Thanks!

**Comment by pieshop** [comment]
Chip - thanks very much for the response 👍

I'll be sure to keep my eyes on this repository. The modern build process would be a very welcome addition and sounds great, along with all the other elements you mention.

Once again thanks for the update.
