### ISSUE TITLE
ConfigPlugin and the tasks module...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#17]
I had a difficult time getting the Application to produce anything for `this.config`. The config was being built and showed up in the assets folder, but during run-time it didn't pull any data. I finally figured out that I needed to include the tasks module. I was going to recommend documenting this on the wiki config page or somewhere, but now I see that there is no "tasks" module listed in the "dist" folder.

I'm just curious, is this is being handled differently in 0.4.0?

**Comment by ericente** [comment]
The Tasks module will be done away with in SpringRoll 0.4. You can see examples of the new loading method here: https://github.com/SpringRoll/SpringRoll/issues/3

You will still be able to have the app automatically load a config file by setting the configPath property in the ApplicationOptions object.

**Comment by bigtimebuddy** [comment]
@probityrules Here's a Wiki page which describes the [Config System](https://github.com/SpringRoll/SpringRoll/wiki/Config-System)

**Comment by probityrules** [comment]
Yeah, I was running with that as my guide, but 0.3.8 needed the extra Tasks piece not mentioned there to handle the run-time `app.config` property setup, thus my initial confusion. From the above, my working assumption is that 0.4.0 will automatically have `app.config` set up if the `configPath` property is provided on Application instantiation.

**Comment by bigtimebuddy** [comment]
Yeah, that's correct.
