### ISSUE TITLE
How to use DragManager and HitArea at the same time

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#18]
Hi,
We have a movie clip which contains several movie clips inside it.
We are trying to hide/show the individual movie clip by using Dragmanager and HitArea.
We need to hide/show individual movie clip on Drag event.

**Comment by yanshcherbakovatredspace** [comment]
This is a support question that has been lingering for sometime. If anyone objects otherwise, I will close this issue shortly.
