### ISSUE TITLE
SpringRoll v1 to v2 Migration Tips

### ISSUE THREAD

**Issue by chipbell4** [SpringRoll/SpringRoll#187]
In SpringRoll v2, we've been pulling out a lot of core things in favor of making the library smaller, and more flexible for end developers. However, a lot of devs do rely some of the built-in functionality around rendering, playing sound, and preloading items. Our current intention is to provide example integrations and templates to bridge this gap for developers. In that spirit, for what all functionality/libraries would developers like examples, to give them a better springboard for starting out a project?

**Comment by gbhkit** [comment]
ANIMATION:
I don't know how widely-used the SpringRoll **Animator** class is (I never used it directly myself), but it has some potentially useful behaviors such as 
 - keeping audio in sync with visuals (by skipping frames if necessary)
 - using keyframed timelines, for event triggering on playback and timeline navigation ("gotoandPlay")

**Comment by gbhkit** [comment]
SCALING:
SpringRoll 1 has a **scaling** system to allow an app to fill its container, and to support "responsive" display of games, using the concept of a "title safe" area and expanded coverage. To be honest, I find the existing system a bit bewildering, but adapting to multiple screen aspect ratios is still a requirement.

**Comment by gbhkit** [comment]
CAPTIONS:
SpringRoll Studio has a captioning tool, and SpringRoll 1 has hooks between the VOPlayer and the display of captions using the output of the tool.

**Comment by probityrules** [comment]
☝️ - I've generally found the functionality of the VOPlayer (running pauses, functions, etc, in addition to audio) and captions setup (including SpringRoll Studio's GUI for creating them) to be super-helpful in streamlining the captioning process.

**Comment by jeremymccurdy-redspace** [comment]
Closing this now, as all devs should have long ago migrated to SR2
