### ISSUE TITLE
Rectangle object is not responsive

### ISSUE THREAD

**Issue by suneetha15** [SpringRoll/SpringRoll#19]
I have created a Rectangle instance using createjs.Rectangle class. But this is  not responsive. 
I tried adding this to container seems like this cannot be done.
What would be the best way to achieve this?

Here is the Code which I'm using to create rectangle :

 var rect = new createjs.Rectangle(400, 220, 200, 150);

**Comment by theBarge** [comment]
A Rectangle is not a Display Object - merely a data structure. To draw a rectangle, investigate the [Graphics API](http://createjs.com/docs/easeljs/classes/Graphics.html)

**Comment by shruthims91** [comment]
I dont want to draw it on the canvas. I want  to get responsive value of x,y, width and height of certain area on the canvas. So I thought to make use  of rectangle class.   Is there any other option to this?

**Comment by theBarge** [comment]
You may find the [Scale Manager](http://springroll.github.io/SpringRoll/classes/springroll.ScaleManager.html) useful - you can access an instance of the scale manager at Application.instance.scaling if you are in a Springroll game.
