### ISSUE TITLE
Event is not triggering on overlapped display object.

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#20]
I have  two display objects A and B.
Obj B is overlapping on Obj A.
Obj A is inactive, unable to trigger any of the event on Obj A. I want to keep  both the objects active. Please provide some solution to achieve this.

**Comment by bigtimebuddy** [comment]
Please consult the EaselJS docs, forums, etc. This problem doesn't seem specific to SpringRoll.
