### ISSUE TITLE
SpringRoll2 State Manager Typescript issue

### ISSUE THREAD

**Issue by ericente** [SpringRoll/SpringRoll#202]
The new StateManager class is neat, but the way it's structured makes it difficult to use from Typescript. Because it can have any number of properties of any name, we're currently telling TS, "all properties are either of type `Property` _or_ they're a function with the signature of `addField`. When it comes time to access those properties we've added with `addField`, Typescript is like "I don't know whether this is a `Property` or a `Function`, so I can't confirm that those sub-properties you're trying to access are valid or not." This means that to use SpringRoll2 with Typescript, any state manager property use sites must be cast as `Property` - `(someState.paused as Property).subscribe(()=>{})`.

If the object that had the `addField` function on it wasn't the same one that has the arbitrarily-named `Property` values on it, we could be more explicit about what types things are, and Typescript (and I) would be much happier. Maybe making `addField` a static method that requires passing in a reference to the StateManager instance you want to add a field to? Or making the Map of fields into their own object that's a child of StateManager? I can't really think of any solutions that wouldn't be breaking changes right now, but maybe there's some other way...

**Comment by chipbell4** [comment]
I think there's actually another solution here, that's maybe not perfect but will not be a breaking change. We could add another method to `StateManager` that could provide a "guaranteed" type:

```typescript
class StateManager {
  // ...
  getField(name : string) : Property {
    // some JS internals, but basically
    return this[name];
  }
  // ...
}
```

I don't think the name is great, but I think this will allow TypeScript folks to have slightly stronger typing here without all the messy casting. I think that'll allow you to do things like this:

```typescript
someState.getField('paused').subscribe(isPaused => {
});
```

That's my gut reaction, but I'm curious if there is a more idiomatic approach. I'd love your feedback, and also that of @andrewstart and @JonGardner-RedSpace .

In the end, there may be a more clever way to define the typings for `StateManager` such that we don't have to define the extra method in the first place.

**Comment by andrewstart** [comment]
Looking at the current JS implementation, there shouldn't be a function type in the property - it is implemented only as 
```typescript
export class StateManager {
  addField(name: string, initialValue: any): Property;
  [key:string]: Property|undefined;
}
```

**Comment by SmithAF** [comment]
I'm wondering if this is something that could be solved by updating the StateManger to handle generics?

```ts
// Something like this?
class StateManager {
  getField<T>(name : string, type?: T) : Property<T> {
    return this[name];
  }
}
```

**Comment by chipbell4** [comment]
@ericente We had an internal discussion and landed with a simpler state management implementation. Here's the PR: https://github.com/SpringRoll/SpringRoll/pull/203

I think this should resolve some TypeScript awkwardness, but feel free to reopen.
