### ISSUE TITLE
Springroll 2.0 and Browserify

### ISSUE THREAD

**Issue by laurieattwobulls** [SpringRoll/SpringRoll#209]
Hi,

I am using Browserify and Springroll 2.0. I was not able to import springroll through:
```
import * as springroll from 'springroll';
```

I had to do:
```
import * as springroll from 'springroll/dist/SpringRoll-umd';
```

It seems to be because there is no main variable in Springroll's package.json, as per this issue on  Browserify's github (https://github.com/browserify/browserify/issues/1541)

Cheers.

**Comment by chipbell4** [comment]
Hi @laurieattwobulls!

Andrew's got a PR up #210 that should resolve that issue. I'll get that merged now. Let me know if you still encounter issues
