### ISSUE TITLE
Unable to preload sound files

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#22]
I have some audio files which I need to preload to the state  before it starts playing.
Here is the code which I used to preload -
        var obj = new springroll.Sound();
        obj.preloadSound('sample_Audio');

I am getting an error : "springroll.Sound was asked to preload sample_Audio but it is not a registered sound!"

Could you please help me to resolve this  error?

**Comment by theBarge** [comment]
Please refer to https://github.com/SpringRoll/SpringRoll/wiki/Config-System for info on how to set up the necessary metadata. Thanks!
