### ISSUE TITLE
Debugger assertions still being hit in release build.

### ISSUE THREAD

**Issue by peterdfinn** [SpringRoll/SpringRoll#222]
I'm diving into SpringRoll 2 for a new project I'm working on, and as I was looking at the documentation, I was very happy to see that there is an easy way to put assertions in code. However, I have discovered that even when I build my game with "npm run build:release", assertions will still fire off if they fail. Is there a way to create assertions that will be active in a debug build but absent in a release build?

**Comment by jeremymccurdy-redspace** [comment]
This is an old issue, so I'm going to close it out. 

Just in case anyone is wondering, the debugger can be disabled by calling `Debugger.enable(false);`. You can pass in a build environment variable if you want this to happen automatically on non-dev builds.
