### ISSUE TITLE
How to  get the details of currently running animations

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#23]
Is there any option to know about currently running animations details ?

**Comment by theBarge** [comment]
This is a good question - we would recommend keeping track of this on your own, perhaps by adding a reference to the instance or `AnimatorTimeline` when starting an animation, and clearing that reference when the animation completes or is cancelled. You can use the `onComplete` and `onCancelled` callback parameters for this in `Animator.play`. 

There is a private variable in Animator that tracks what timelines are animating, but we do not recommend the use of private variables as the class's implementation details could change at any time.
