### ISSUE TITLE
UserData.read doesn't appear to read from host page's localStorage.

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#234]
I'm seeing `null` for a data value when trying to use `UserData.read`. I _think_ it may be related to this line where it doesn't seem to be passing the enclosing function's `name` parameter upstream to the host page's `localStorage` handler:
https://github.com/SpringRoll/SpringRoll/blob/2e400b7f72712b292479080ed8da0ae3b3e5de0e/src/state/UserData.js#L65

**Comment by chipbell4** [comment]
Okay! @902seanryan will look into this very shortly!

**Comment by chipbell4** [comment]
This should be resolved in the latest `master`. I'll update when `2.0.3` is also released and on NPM

**Comment by chipbell4** [comment]
Should be resolved now on NPM
