### ISSUE TITLE
Controller doesn't update key state on focus loss

### ISSUE THREAD

**Issue by ericente** [SpringRoll/SpringRoll#248]
If a key is held down while the window loses focus, Controller never gets the keyUp event until the button is pressed and released again. I'm using this as a workaround, where `this.keyboard` is an instance of `Controller`:

```
window.onblur = ()=>{
    for(let key of Object.keys(this.keyboard.buttons)){
        this.keyboard.buttons[key].updateState(2);
    }
};
```

**Comment by andrewstart** [comment]
And as more context for your workaround and this bug, you are forcing all keys to be released when focus is lost, because there is no current or planned API to determine which keys are currently pressed, so there is no way to determine what keys are released while focus is not held.

**Comment by JonGardner-RedSpace** [comment]
PR: https://github.com/SpringRoll/SpringRoll/pull/249
