### ISSUE TITLE
Audio issue in windows 8

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#25]
Game audios are not playing properly in the headphones.We can hear only in right headphone.

**Comment by probityrules** [comment]
If this happens in Chrome, I believe it's a SoundJS bug. It's fixed in the NEXT version of SoundJS: https://github.com/CreateJS/SoundJS/commit/70a812a564641e2f49b6edcb567efd75243b0e6c

One work-around we've found is to set the panning to something like `0.0001`.

**Comment by andrewstart** [comment]
We've also implemented that workaround in the upcoming release of SpringRoll (0.4).

**Comment by praveen4565** [comment]
Thanks for the response.

For the work around how to set the panning, we tried adding panning in vo.json file but it did not work. Please advice.

Thanks.

**Comment by bigtimebuddy** [comment]
@praveen4565 Released SpringRoll v0.3.9 with the Chrome audio fix.
