### ISSUE TITLE
VOPlayer quirk causes VO tracks to play simultaneously...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#27]
I've noticed that the VOPlayer's "single audio track playing" becomes unreliable when additional VO is triggered by the cancelledCallback function. For example, in the following case:

        app.voPlayer.play('ready-set', function(){app.voPlayer.play('go')}, function(){app.voPlayer.play('restart-race')});
        // ... a few milliseconds later ...
        app.voPlayer.play('jump-the-gun');

If "ready-set" is interrupted in the middle by "jump-the-gun", "ready-set" stops playing, but "jump-the-gun" and "restart-race" begin playing simultaneously. When "restart-race" finishes, it is immediately followed by "go", even though it was the success callback for "ready-set", not "restart-race".

I can probably work around the above using something like `setTimeout(f, 1)` to break out of the current processing flow (or restructuring the more complex design I simplified into the above test case), but I wanted to make note of this here in case it's easily addressed on the SpringRoll side of things.

**Comment by bigtimebuddy** [comment]
Good catch @probityrules, I'll look into this. Thanks for the example, that's helpful.
