### ISSUE TITLE
Fatal error: Failed to execute exit code of #128 || SpringRoll studio

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#28]
https://cloud.githubusercontent.com/assets/13066894/9326697/569ce53c-45b9-11e5-848d-0f1ca3fbad0b.png

Fatal error: Failed to execute "git ls-remote --tags --heads git://github.com/SpringRoll/SpringRoll.git", exit code of #128

When we do  cleanAll from the task and when we try to build the project, we are getting this error.

Please suggest.

**Comment by probityrules** [comment]
We had the same issue with pulling the jquery repo yesterday. It seemed that the repo was down on github's end for an hour or so. It began working again later in the day.

**Comment by bigtimebuddy** [comment]
Github had some service issues yesterday (August 17, 2015) https://status.github.com/messages
