### ISSUE TITLE
ResizeHelper's use of screen.height

### ISSUE THREAD

**Issue by andrewstart** [SpringRoll/SpringRoll#283]
Question: What are these lines in ResizeHelper supposed to solve?
https://github.com/SpringRoll/SpringRoll/blob/5856d7a79739901df73996b3dc816f338dce7516/src/scale-manager/ResizeHelper.js#L115-L118
For me, they were the cause of a scaling issue as they were reporting a (somewhat) larger value inside the game's iframe than the iframe dimensions. I found that just using `document.documentElement.clientHeight` (and width) across the board worked correctly.

**Comment by 902seanryan** [comment]
@andrewstart sorry we didn't follow up on here properly, but we took your advice and updated that section in [v2.3.3](https://github.com/SpringRoll/SpringRoll/releases/tag/2.3.3) released a couple weeks ago.
