### ISSUE TITLE
IE | Horizontal scroll bar issue

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#29]
In IE browser I am getting horizontal scroll bar. Am not sure with on what scenario am getting. Is there any work around to eliminate this issue?

**Comment by theBarge** [comment]
More info please - what version of IE? What are the dimensions of your canvas? Screenshots would also help, or some way we could reproduce what you are seeing.

**Comment by praveen4565** [comment]
Browser version : IE 11
Canvas : "width": 988,
               "height": 565



![iebrowser](https://cloud.githubusercontent.com/assets/13066894/9360553/778894fc-46b4-11e5-97fe-67ddd6f30358.png)

**Comment by theBarge** [comment]
Two thoughts from our team:
* Make sure that the generated libraries.css file is being included in your html file (`<link rel="stylesheet" href="assets/css/libraries.css">`) by default
* Implement a solution similar to this:
```
body {
    background-color: #fff !important;
    //needed so that we don't get scroll bars in IE
    overflow: hidden;
}
```

**Comment by praveen4565** [comment]
Thank you @theBarge . Working fine now.

**Comment by praveen4565** [comment]
Hi, If we deploy the application library.css will be regenerated. If we paste the above code it will not be retained. Is there any work around to make retain in library.css

**Comment by theBarge** [comment]
The recommended way to fix this is to add a less or css file in the `main` section in `springroll.json`. The grunt build process will generate a /deploy/css/main.css file, which you can then link in the head of your html file.
