### ISSUE TITLE
Title safe not working for background image

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#33]
We have referred titleSafe in game.json, and in game panel we have added this.gameScaling = this;
Here all the game elements are getting scaled except background image, screen shot below

![image](https://cloud.githubusercontent.com/assets/13066894/9384845/a864a748-4770-11e5-8fe3-8646aa948677.png)

**Comment by bigtimebuddy** [comment]
Is the background have an instance name of `background`?

**Comment by praveen4565** [comment]
@bigtimebuddy ..Yes, Please find the below code for more information.
In gamepanel
p.setup=function(){
	this.gameScaling = this;
        this.background = new Bitmap(images.GameBackground);
        this.addChildAt(this.background,0);
};

in game.json[Inside scaling folder] : 

{
"gameScaling":{
"titleSafe": true
}
}

**Comment by bigtimebuddy** [comment]
If you change the background name to something else, like `bg` or `backgroundMain`, or whatever, it should fix the background. Panel items with the name `background` get auto-scaled responsively. If you're also scaling the whole panel (which  you are in this case), the image gets scaled twice. We're working on this functionality to make it less cryptic. See if that makes a difference.

**Comment by praveen4565** [comment]
below work around I tried yesterday.

p.setup=function(){

this.gameScaling = this;
//this.background = new Bitmap(images.GameBackground);//eliminated this line of code
//this.addChildAt(this.background,0);
var  background = new Bitmap(images.GameBackground);// changed to this.
this.addChildAt(background,0);
}

After doing this, some images i am adding in substates, those are scaling but image positiion is not proper, Can you suggest some other work around for this

**Comment by bigtimebuddy** [comment]
@praveen4565 please clarify what you're asking and show another screen shot, provide more code.

**Comment by yanshcherbakovatredspace** [comment]
@praveen4565 Have you been able to resolve this? If not, as @bigtimebuddy requested, could you please provide another screenshot and a pastebin of your code?

**Comment by yanshcherbakovatredspace** [comment]
Closing this issue.
