### ISSUE TITLE
Get multiple instance of sprite image in springRoll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#36]
How can we use existing sprite animation multiple times in springRoll framework.

Please advice.

Thanks.

**Comment by bigtimebuddy** [comment]
If you're using `BitmapMovieClip`, you can use the [clone](http://springroll.github.io/SpringRoll/classes/springroll.easeljs.BitmapMovieClip.html#method_clone) method to make a copy of the animation.

```
var clip = new BitmapMovieClip(atlas, data);
var clipCopy = BitmapMovieClip.clone(clip); // makes a copy
```

**Comment by praveen4565** [comment]
We are using spritesheet for an object animation. We need to create multiple instances of the same animation to run at the same time.

**Comment by bigtimebuddy** [comment]
Are you using the `createjs.SpriteSheet` object for your animation?

**Comment by praveen4565** [comment]
Thanks, we did tried using BitmapMovieClip as you suggested and it worked for us.

Thank you so much.

**Comment by praveen4565** [comment]
Hi

titleSafe is not working for cloned animation objects.

We are adding and making a copy of sprite animation in a sub-state. Here these objects are not scaling (responsive).

Please advice.

Thanks

**Comment by bigtimebuddy** [comment]
Hmm... BitmapMovieClip has nothing to do with the scaling. I suspect you are clone the new clip after the state has already been initialized/loaded (after when the scaling is setup). If you add a display object after the state has been setup, you need to manually add the item to the ScaleManager using [`addItem`](http://springroll.github.io/SpringRoll/classes/springroll.ScaleManager.html#method_addItem). For instance:

```js
var clipClone = BitmapMovieClip.clone(clip);
app.scaling.addItem(clipClone);
```
