### ISSUE TITLE
How to change x and y coordinates of dragging object?

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#37]
Using drag manager, able to drag the object but while dragging need to push the object(above the pointer).
Could you please provide information how best this can be done?

**Comment by bigtimebuddy** [comment]
Please explain more thoroughly. Not sure I understand what you're looking to do.

**Comment by shruthims91** [comment]
The query is about how to get the x and y co-ordinates of the object that is being dragged?

**Comment by andrewstart** [comment]
Currently the way to do this is to modify the DragManager's [_dragOffset](http://springroll.github.io/SpringRoll/classes/springroll.easeljs.DragManager.html#property__dragOffset) point after dragging has started. This is the position relative to the object's origin that the mousedown/touchstart event happened at - changing it to 0,0 would make the object's origin stick to the cursor during the drag.

**Comment by andrewstart** [comment]
Version 0.4.10 added a `dragOffset` parameter to DragManager's [addObject()](http://springroll.io/SpringRoll/docs/classes/springroll.easeljs.DragManager.html#method_addObject) function - this allows you to force an object to be dragged from a specific position each time.
