### ISSUE TITLE
Potential bug in springroll.easeljs.AssetManager unloadAll method

### ISSUE THREAD

**Issue by Jacob-Geb** [SpringRoll/SpringRoll#38]
I think there's might be a copy-paste error in the unloadAll method of the AssetManager (springroll/dist/modules/easeljs-ui.js - line 2499).

    var i, length;
    for(i = 0, length = loadedAssets.length; i < length; ++i)
    {
        if (images[asset])
        {
            images[asset].src = "";
            delete images[asset];
        }
    }

I'm assuming that 'asset' should be 'i'

**Comment by bigtimebuddy** [comment]
Thanks Jacob. Good catch.
