### ISSUE TITLE
Using Tile map in springroll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#4]
Is there any springroll class which helps to work with tile map generated from .tmx files.?
I searched related to this in the SpringRoll API list, but could not found.

**Comment by bigtimebuddy** [comment]
SpringRoll is agnostic of how things are displayed. There are some convenience classes and methods for working with certain types of content but generally SpringRoll does not have support for any particular map file formats. However, SpringRoll supports both [PIXI.js](http://pixijs.com)  and [EaselJS](http://easeljs.com), so if there are any plugins or tools available for those rendering libraries which utilize TMX files, it should be fairly easy to integration into a SpringRoll-based project.
