### ISSUE TITLE
Fatal error: Failed to execute exit code of #128

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#41]
Please let me know what is this error and how to resolve.

I am getting this error after creating new project, when I build the application at first.

![pbs_install_task_error](https://cloud.githubusercontent.com/assets/13066894/9680884/b626730e-5317-11e5-94e4-7e47641de39e.PNG)

**Comment by bigtimebuddy** [comment]
Not an issue with SpringRoll or SpringRoll Studio. Seems to be an issue with Bower and your current setup. Try [Googling](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bower%20failed%20to%20execute%20git%20ls-remote) the issue. Here is [one potential solution](http://stackoverflow.com/a/21790275): 

```bash
git config --global url."https://".insteadOf git://
```

**Comment by praveen4565** [comment]
It's because of anti-virus security. After giving permission to github.com url got resolved.

**Comment by bigtimebuddy** [comment]
Good to know!
