### ISSUE TITLE
passing some string from one state to another state?

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#42]
How can I pass a string from one state to other state?

**Comment by bigtimebuddy** [comment]
You could get a reference to another state with the StateManager and set the property on the other state:
```js
// Inside "game" state
var state = this.manager.getStateById("title");
state.someProperty = "Something";
```
Or you could store that property on the application if you need multiple things to read that string.
```js
this.app.someProperty = "Something";
```
