### ISSUE TITLE
query on soundbutton

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#43]
As per my understanding soundbutton accept a sprite image having (normal,hover,click).. which will be handled by soundbutton itself.

My query is, assume I have a requirement where I need to show hover state of a button for some condition? How can I do this?

**Comment by andrewstart** [comment]
If your button state is just a toggle-able state, like selected or highlighted, then you just provide that data to the button when initializing it:
```javascript
var myButton = new Button({
    image: images.MyButtonImage,
    priority: ["highlighted", "disabled", "down", "over", "up"],
    up: <up state source rectangle within images.MyButtonImage>,
    over: <over state source rectangle within images.MyButtonImage>,
    down: <down state source rectangle within images.MyButtonImage>,
    disabled: <disabled state source rectangle within images.MyButtonImage>,
    highlighted: <highlighted state source rectangle within images.MyButtonImage>,
});
//enable highlight state - priority Array from initialization specifies 
//that it overrides all other states
myButton.highlighted = true;
//disable highlight state when we are done
myButton.highlighted = false;
```

If you want your button hover state to vary based on a condition, you would need to modify the hover state source rectangle in the [Button's _stateData dictionary](http://springroll.github.io/SpringRoll/classes/springroll.easeljs.Button.html#property__stateData):
```javascript
var myButton = new Button(<initialization data>);
//change the source rectangle for the over state. Each state in _stateData
//may also have a 'trim' property that describes transparent padding that has been
//trimmed off of the button state (and source rectangle).
myButton._stateData.over.src = new createjs.Rectangle(200, 100, 50, 50);
```
If you use this second method, I suggest making a class to extend Button or SoundButton to do it with.
