### ISSUE TITLE
dynamically calling state.

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#44]
Before answering to my question. I have some queries.

1)  Can I have multiple states like
Assume rather using game state can I have (game1,game2,game3) states like this? If Yes, then how do I load anyone of state based on some condition?

for example :+1: 
this.manager.next("game1")// sample code.

it there any method in the Statemanager which will accept string [state name] and triggers to that state

**Comment by bigtimebuddy** [comment]
Yes, you can add multiple state the way you do the other states, by adding another state to the application states (usually in your **main.js** file):

```js
app.once('init', function()
{
	this.states = {
		title: new TitleState(),
		game: new GameState(),
		result: new ResultState()
	};
});
```

The API you're looking for on StateManager is `state` (http://springroll.github.io/SpringRoll/classes/springroll.StateManager.html#property_state), for instance:

```js
// Goes to the ResultState (in the example above)
this.manager.state = "result";
```
