### ISSUE TITLE
Is there a support to SVG images in SpringRoll framework? 

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#45]
Is there a support to SVG images in SpringRoll framework?

**Comment by andrewstart** [comment]
SpringRoll doesn't have anything directly to do with the rendering. EaselJS supports SVG as images with the [Bitmap class](http://createjs.com/docs/easeljs/classes/Bitmap.html).

**Comment by chetansind** [comment]
Does latest springRoll version support SVG, i was looking for something similar to SVG path animation or itself where i can get/update the path value (d value) dynamically?

**Comment by andrewstart** [comment]
No. You can try parsing the SVG yourself, but SpringRoll still leaves anything like SVG support to the display libraries, and EaselJS does not support animated SVGs to my knowledge.
