### ISSUE TITLE
Is there a event/method triggering on browser resize in springRoll framework?

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#46]
Is there a event/method triggering on browser resize in springRoll framework?

And also is there a event/method to reload/refresh the game/browser in springRoll.

**Comment by bigtimebuddy** [comment]
There is a resize event:

```js
app.on('resize', function(w, h)
{
	// application is resized, w is the new application width
	// and h is the application height
});

// manually trigger a resize
app.triggerResize();
```

There's no method to reload the game.  You can reload the browser with `window.location.reload()`.
