### ISSUE TITLE
How to load pre-audio files separately for each state?

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#47]
Is there any option  to preload audio files separately for each state (title, intro, game etc)? 
Currently I am pre-loading all the audio files in the title state which causing more delay in loading the game initially.

**Comment by bigtimebuddy** [comment]
If you're using SpringRoll 0.4, you can preload a list of sounds by passing an object like this into the preload array options. The `sounds` option contains a list of sound aliases to preload.

```json
{
	"sounds": ["VOLine1", "SFX1", "SFX2"]
}
```
