### ISSUE TITLE
To detect object collision while dragging.

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#48]
Drag manager has been used to drag object but unable to detect object collision with any other static object. Please let us know how to detect object is colliding each other when moving.

**Comment by yanshcherbakovatredspace** [comment]
Collision detection is not something that will be in the core library, but will be available soon via a plugin. Physics and any such functionality will always be a plugin to be used with Springroll and won't be part of the core library.

Stay tuned for a collision detection plugin.
