### ISSUE TITLE
Complete games source code included in examples? 

### ISSUE THREAD

**Issue by beveretthealy** [SpringRoll/SpringRoll#5]
I'm wondering if you could upload complete source code for some of the games that were created with or ported to springroll (specifically those using EaselJS as the primary display). It would be an awesome help in figuring out some of the intended uses of various parts of the framework and also to get some ideas on how overall game architecture looks in springroll.

Thanks!

**Comment by bigtimebuddy** [comment]
Eventually we will do this. In the mean time, please contact PBS and they will be able to provide some full game samples.
