### ISSUE TITLE
loading images once which is required for multiple states.

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#50]
I need to load the image once which is required for multiple states.

Example : Assume I have 3 states called state1,state2 and state3. Normally we refer the images in assets folder with name of state1.json,, etc.. 
I have some images which is required for all the states. As of now I am referring the images to one json and I am loading into all the states. Is this approach is fine? or is ther any method help me to eliminate loading same images mutliple time?

this.states = {
                superState: new SuperState({
				next: 'title', 
				previous: 'title',
				preload: [].concat(
                    fla.ImaginationBorder,
                    fla.Daniel_SUPER_anim_super,
                    assets.game                                  //Same Asset for all the states
),
				scaling: "panel"
			}),
			cowState: new CowBoyState({
			    next: 'title',
			    previous: 'title',
			    preload: [].concat(
                    fla.ImaginationBorder,
                    fla.Daniel_SUPER_anim_cowboy,
                    assets.game                                  //Same Asset for all the states
                    ),
			    scaling: "panel"
			}),
			explorerState: new ExplorerState({
			    next: 'title',
			    previous: 'title',
			    preload: [].concat(
                    fla.ImaginationBorder,
                    fla.Daniel_SUPER_anim_explore,
                    assets.game                                 //Same Asset for all the states
),
			    scaling: "panel"
			})

  }; 
.

**Comment by praveen4565** [comment]
Can anyone suggest for above  concern?

**Comment by bigtimebuddy** [comment]
Try preloading the assets before any of the states are created as part of the Application setup:
```js
// Listen for when the config has been loaded
app.once('configLoaded', function(config, assets)
{
	// add the global assets to the loading assets
	// these will get loaded immediate and will be available
	// on 'init' and will exist until you app.unload them
	config.assets.game.forEach(function(asset)
	{
		// Add the callback to handle the image
		asset.complete = onAssetComplete;
		assets.push(asset);
	});
});

// add createjs assets to the global images, if necessary
function onAssetComplete(img, asset)
{
	if (img.nodeName == "IMG")
		window.images[asset.id] = img;
}
```
