### ISSUE TITLE
Filter not working for movie clip

### ISSUE THREAD

**Issue by ashokshettym** [SpringRoll/SpringRoll#52]
Hi, 
I am trying to achieve GlowFilter effect for the movie clip on load for few seconds using filter. But filter is not working.

**Comment by andrewstart** [comment]
This is an EaselJS/GlowFilter issue, not SpringRoll. Make sure you are using [EaselJS's filters properly](http://www.createjs.com/docs/easeljs/classes/Filter.html) and follow any instructions given by your GlowFilter class.

**Comment by bigtimebuddy** [comment]
@ashokshettym Please note that EaselsJS's display filters are very expensive performance-wise and not suitable for mobile or slower performing devices. It's recommended that you work-around their usage by pre-baking filters as images or using solid shapes to create an "outline" or "highlight" around the an object.
