### ISSUE TITLE
Playing animation based on frame number of a movieclip.

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#53]
I need to play animation based on some frame number as condition. I tried using the below code

example:
  this.panel.currentAnimation.on("tick", function (e) {
if (((this.panel.currentAnimation.timeline.position) % this.panel.currentAnimation.timeline.duration) === 6) {
// some audio play
};

if (((this.panel.currentAnimation.timeline.position) % this.panel.currentAnimation.timeline.duration) === 30) {
// play some movieclip
};

};

This is perfectly working for desktop. When it comes to mobile, frame rates are different and unable to satisfy the above condition.

Please give some suggessions to overcome from this.

**Comment by andrewstart** [comment]
Instead of relying on each frame getting used during the animation (which may happen multiple times if your refresh rate is faster than the animation's framerate), use [JavaScript in your animation's timeline in flash](http://www.adobe.com/devnet/createjs/articles/using-flash-pro-toolkit-createjs.html#articlecontentAdobe_numberedheader_8) to trigger events that you could listen to.

**Comment by praveen4565** [comment]
Thanks @andrewstart  , below is the sample code which is generated from fla. In this code you can find a variable called frame_70 which is triggering when actual frame enters.But, my question is how do I get this event inside the any states in springroll?

Example:

(libSuper.balloon_OBJECT_super = function(mode,startPosition,loop) {
	
	var frame_70;
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{idle:0,action:64,memory:138});

	// timeline functions:
	frame_70 = this.frame_70 = function() {
		//playSound("Magic_carpet_loopwav");
	}


}).prototype = p = new MovieClip();
p.nominalBounds = new Rectangle(327.3,-176.3,112,309.4);

**Comment by praveen4565** [comment]
How can I bind timeline function to springroll state?

**Comment by bigtimebuddy** [comment]
Timeline functions ("Actions" in Flash) are automatically bound to the symbol instance. So calling something like `this.dispatchEvent('doSomething');` would call that on the MovieClip. Then from within your state you'd do something like this: 

```js
var clip = new libSuper.balloon_OBJECT_super();
clip.addEventListener('doSomsething, function()
{
     // this function is bound to the state
}.bind(this)); // where this = state
```

**Comment by praveen4565** [comment]
I have a question. I have implemented this, but when I run this application in device, events are not triggering[sometime it triggers and sometime not]. And Animations are too slow. Is there any particular reason for it?

**Comment by bigtimebuddy** [comment]
Are you playing your animations through SpringRoll's Animator? Or just by calling `clip.play()`?

Work on improving the performance of your animations by reducing the use of vectors and replacing pieces with bitmaps, remove any use of dynamic filters (blur, glow, etc), [optimize keyframes](https://github.com/SpringRoll/FlashToolkit#optimizingoptimize-keyframe), remove any masks. 

Also, performance with EaselJS is really limited in context2d. If you have more than one animating movie clip on the screen at once, make sure you are caching the clips or display objects that aren't moving so they don't need to be redrawn every frame.
