### ISSUE TITLE
Scale Manager - bottom cut off (Safari iPad)

### ISSUE THREAD

**Issue by Jacob-Geb** [SpringRoll/SpringRoll#54]
I've essentially got an empty app, with only a panel background (scaling set to cover-image).
Scaling works fine on all major desktop browsers, as well as chrome on the iPad.
However on iPad Safari, a chunk of the screen is cut off. (iPad 4 - ios 7.1)

[app](https://s3-ap-southeast-2.amazonaws.com/2m.pbskids.ssq/scaleFail/index.html) &  [code](https://github.com/Jacob-Geb/ScaleTest)

cheers,
-J

chrome
![photo 1](https://cloud.githubusercontent.com/assets/12044510/10154397/1cc9b01c-66aa-11e5-8637-2e684e66719b.PNG)
safari
![photo 2](https://cloud.githubusercontent.com/assets/12044510/10154399/1f9ca7ea-66aa-11e5-9922-9bc04ba91f75.PNG)

**Comment by bigtimebuddy** [comment]
Jacob, could you put those screenshots right into this thread? You can drag them onto the comment area. Thanks.

**Comment by bigtimebuddy** [comment]
@Jacob-Geb If you rotate on Safari and the UI becomes minimized (soft fullscreen) does it become un-cropped?

**Comment by Jacob-Geb** [comment]
Rotating the screen will work for iPhones ( I've attached screen grabs below), but the UI does not minimise on the iPad.

iphone5:
![iphone5](https://cloud.githubusercontent.com/assets/12044510/10154657/9b8c3138-66ad-11e5-811c-951d74018f35.PNG)
iphone6:
![iphone6](https://cloud.githubusercontent.com/assets/12044510/10154658/9b8c2b2a-66ad-11e5-960b-0129bfc3ceca.PNG)

**Comment by bigtimebuddy** [comment]
My hunch is that this isn't a ScaleManager issue and is most likely a CSS issue with iOS 7 on the iPad. The canvas takes it's resizing cues from the `#frame` DOM element. I can't reproduce because we don't have an iOS7 device. If you can help isolate whether it's a CSS or SpringRoll issue, that would be very useful.

**Comment by Jacob-Geb** [comment]
Sure, I'll probably have some free time next week.

**Comment by Jacob-Geb** [comment]
I messed around with it a bit (there seems to be more than one bug regarding css on ios7 ).

So changing the frame position from absolute to fixed in the css fixes the issue.. no pun intended.
That being said, I haven't thoroughly made sure that the change doesn't cause new problems on other devices or browsers.

**Comment by rckincade** [comment]
@Jacob-Geb - I am currently building an issues list for dev/fixes work. Can you add subsequent findings, or resolve this issue if it's not a bug with SpringRoll? Thanks.
