### ISSUE TITLE
Help wanted: how to make anti alias for text in springRoll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#55]
Help wanted: 
How to make anti alias for text in springRoll

For text we are getting blur issue in iPhone/smaller devices.

**Comment by bigtimebuddy** [comment]
I'm going to close this issue because it seems not specific to SpringRoll or it's APIs. Please look at the Text and/or DOMElement classes in EaselJS for issues on rendering text.
