### ISSUE TITLE
Infinite scrolling of background image

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#56]
I need to scroll multiple images at a time with different speed. I have done the below approach. Its working fine for desktop, but when it comes to mobile its too slow. Is this standard way to do it in springroll or is there any better way to do it? 

Example :+1: 

//Constants for scrolling background image.
app.MAX_SPEED_BACKGROUND=0.2;
	app.MAX_SPEED_FOREGROUND=2;
	app.MAX_SPEED_MIDGROUND=1;
    app.MAX_SPEED_GROUND=1.5;

// In Panael
_background = { // {Object} Twin backgrounds for infinte scroll
        FGround: null, // {Bitmap} Foreground background
        FGround1: null, // {Bitmap} Foreground1 background
        Ground: null, // {Bitmap} Ground background
        Ground1: null, // {Bitmap} Ground1 background
        BGround: null,// {Bitmap} background background
        BGround1: null,// {Bitmap} background1 background
        MidGrd: null,// {Bitmap} MiddleGround background
        MidGrd1: null// {Bitmap} MiddleGround1 background
    };
-------------------------------------------------------------
// In some state
 //Background
                _background.BGround = new Bitmap(images.BG_Jungle);
                _background.BGround.x = 0;
                _background.BGround1 = new Bitmap(images.BG_Jungle);
                _panel.addChild(_background.BGround);
                _panel.addChild(_background.BGround1);
//Middle Ground
                _background.MidGrd = new Bitmap(images.MidGround_Jungle);
                _background.MidGrd.x = 0;
                _background.MidGrd1 = new Bitmap(images.MidGround_Jungle);
                _panel.addChild(_background.MidGrd);
                _panel.addChild(_background.MidGrd1);
//Ground
                _background.Ground = new Bitmap(images.Ground_Jungle);
                _background.Ground.x = 0;
                _background.Ground1 = new Bitmap(images.Ground_Jungle);
                _panel.addChild(_background.Ground);
                _panel.addChild(_background.Ground1);
//ForeGround
                _background.FGround = new Bitmap(images.Foreground_Jungle);
                _background.FGround.x = 0;
                _background.FGround1 = new Bitmap(images.Foreground_Jungle);
                _panel.addChild(_background.FGround);
                _panel.addChild(_background.FGround1);
                springroll.Application.instance.on('update', this._update);

 var i = 1, bG = 1, mdGrp = 1, fGrd = 1;
 p._update = function (elapsed) {
        //alert(elapsed);
        if (mdGrp % 2 === 0) {
            if (parseInt(_background.MidGrd1.x) === 0) {
                mdGrp++;
                _background.MidGrd.x = _background.MidGrd1.image.width - 2;
            }
        } else {
            if (parseInt(_background.MidGrd.x) === 0) {
                mdGrp++;
                _background.MidGrd1.x = _background.MidGrd.image.width - 2;
            }
        }

        if (bG % 2 === 0) {
            if (parseInt(_background.BGround1.x) === 0) {
                bG++;
                _background.BGround.x = _background.BGround1.image.width - 3;
            }
        } else {
            if (parseInt(_background.BGround.x) === 0) {
                bG++;
                _background.BGround1.x = _background.BGround.image.width - 3;
            }
        }
        if (_background.FGround !== null) {
            if (fGrd % 2 === 0) {
                if (parseInt(_background.FGround1.x) === 0) {
                    fGrd++;
                    _background.FGround.x = _background.FGround1.image.width - 3;
                }

            } else {
                if (parseInt(_background.FGround.x) === 0) {
                    fGrd++;
                    _background.FGround1.x = _background.FGround.image.width - 3;
                }
            }
            _background.FGround.x -= app.MAX_SPEED_FOREGROUND;
            _background.FGround1.x -= app.MAX_SPEED_FOREGROUND;
        }

        if (i % 2 === 0) {
            if (parseInt(_background.Ground1.x) === 0) {

                i++;
                _background.Ground.x = _background.Ground1.image.width - 3;
            }

        } else {
            if (parseInt(_background.Ground.x) === 0) {
                i++;
                _background.Ground1.x = _background.Ground.image.width - 3;
            }
        }
        _background.Ground.x -= app.MAX_SPEED_GROUND;
        _background.Ground1.x -= app.MAX_SPEED_GROUND;

        _background.BGround.x -= app.MAX_SPEED_BACKGROUND;
        _background.BGround1.x -= app.MAX_SPEED_BACKGROUND;

        _background.MidGrd.x -= app.MAX_SPEED_MIDGROUND;
        _background.MidGrd1.x -= app.MAX_SPEED_MIDGROUND;
    };

**Comment by bigtimebuddy** [comment]
This question is not specific to SpringRoll or it's APIs so I'm going to close. Please investigate more in-depth the EaselJS renderer--that is causing your performance issues on mobile. 

Some recommendations: consider using SpriteStage (WebGL) drawing in EaselJS to increase performance for this type of parallax drawing. Also, we've found creating versions of your background images that are half-size (reducing overall memory size) helps performance on lower performing mobile devices. You also have four layers, moving all the time. You may want to consider reducing this on mobile to 2 (or 3).
