### ISSUE TITLE
To stop Background music

### ISSUE THREAD

**Issue by ashokshettym** [SpringRoll/SpringRoll#57]
Hi, 
I am using "this.game.music" to play the audio file in the background continuously. To stop ,am using this.game.music ="". It works in some cases and not all the time. Is there any thing am i missing to stop the background audio file. 
Also, Is there any other option to play the audio file continuously and to stop when ever required.

**Comment by bigtimebuddy** [comment]
Let's start with the second question. You can set a flag in the JSON where you define the music context to make sure the sound loops. Your **src/config/sounds/music.json** might look like this:
```json
{
	"context": "music",
	"path": "assets/sounds/music/",
	"sounds": [
		"BackgroundMusic"
	]
}
```
This would change to this
```json
{
	"context": "music",
	"path": "assets/sounds/music/",
	"sounds": [
		{
			"id": "BackgroundMusic",
			"loop": true
		}
	]
}
```

You can either do `this.app.music = "BackgroundMusic"` to start and `this.app.music = null` to stop (this approach fades the music in and out when it starts/stops), or you can call `this.app.sound.play("BackgroundMusic")` to start and `this.app.sound.stop("BackgroundMusic")` to stop. 

Let me know if that helps.
