### ISSUE TITLE
Getting keystrokes to an iframed game...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#59]
When testing our games on SpringRoll Connect, if we click the top control bar (outside the iframe game area), the keystrokes are still received by the game.

However, if we embed the iframe link provided by SpringRoll Connect into another web page, the keystrokes are no longer received once we click outside the iframe. Additionally it seems like the game content is three iframe levels deep at this point. Is there an additional step that's required on the hosting page to pass along the keystrokes from the container to the game or should we be using an alternate embed method, not the provided iframe link?

**Comment by andrewstart** [comment]
The Application option [_keepFocus_](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#property_options.keepFocus) (set on the game) attempts to keep focus on the game's iFrame, although this may not be reliable if the Container that is loading the SpringRoll Connect iFrame is itself inside an iFrame.

**Comment by probityrules** [comment]
That seems to work; thanks!
