### ISSUE TITLE
Caching images in springroll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#6]
Is there any class which helps to cache the image object in the springroll? If yes please give sample example

**Comment by beveretthealy** [comment]
If you're using EaselJS display, there is a mixin for the createjs.Container that allows you to cache a container by its bounds: http://springroll.github.io/SpringRoll/classes/createjs.Container.html, this is assuming that you mean drawing multiple bitmaps in a container in one draw call as a separate canvas.

**Comment by bigtimebuddy** [comment]
(I'm assuming you're using the EaselJS Display) Like @beveretthealy said, there is a convenience mixin method on Container called `gotoAndCache()` that will do caching, however, you should look at the docs for EaselJS's `DisplayObject.prototype.cache()` http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#method_cache if you need something more custom. 

We also added a method `gotoAndCacheByBounds()` to `createjs.MovieClip` (see http://springroll.github.io/SpringRoll/classes/createjs.MovieClip.html#method_gotoAndCacheByBounds) which allows you to gotoAndStop on a frame and then cache the result. 

```js
// "lib.MyClip" is a library symbol from Flash
var clip = new lib.MyClip(); 

// cache the "start" labeled frame
clip.gotoAndCacheByBounds('start'); 
```

**Comment by praveen4565** [comment]
Thanks @beveretthealy , @bigtimebuddy. Can i use same for tile map format?
