### ISSUE TITLE
Can BitmapMovieClip animation frames be more like createjs.SpriteSheet's?

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#60]
The CreateJS SpriteSheet format defines a collection of frames (rectangular cuts from the sprite sheet image) and, separately, defines the animation as a series of references to these frames. So for example a swinging pendulum might have 5 frames showing it swing from left to right, but the complete animation would be those 5 frames and then the same in reverse: [1,2,3,4,5,4,3,2,1]. That way only five unique frames need to be defined.

The BitmapMovieClip's initialization data only specifies a start and end to an animation sequence. So in the pendulum example, it seems there would have to be 9 frames specified, although the last four would be cut and pasted from the first four (in reverse). That can become verbose!

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
