### ISSUE TITLE
openPath triggering closed event in Container

### ISSUE THREAD

**Issue by jamieowen** [SpringRoll/SpringRoll#64]
Hey,

More of a usability thing, and not sure if this was intended, but the closed event is triggered as soon as you call openPath on the Container. The reset() method dispatches it by default via _internalIOpen even if nothing has been opened before..

Cheers,

Jamie

**Comment by bigtimebuddy** [comment]
This should be changed. Good catch. 

As a workaround, you could use the Container's `loaded` property in your closed handler to check if it's a "real" closed event.

**Comment by andrewstart** [comment]
Changed for the next release.
