### ISSUE TITLE
Focus events trying to call focus() on null iframe.contentWindow after closing Container.

### ISSUE THREAD

**Issue by jamieowen** [SpringRoll/SpringRoll#65]
Hey,

One other small one, If I have a Container persisting in the background after I have previously used it via openPath / close.  

The _onDocClick handler is still trying to call focus on the null iframe.contentWindow 
https://github.com/SpringRoll/SpringRoll/blob/master/src/container/Container.js#L332-L338
https://github.com/SpringRoll/SpringRoll/blob/master/src/container/Container.js#L633-L636

Would make sense to remove those document focus events on close or check that if the iframe is loaded or not!

Cheers,

Jamie

**Comment by andrewstart** [comment]
It would definitely make sense to only call focus() on iframes that are loaded. I've changed this for the next release.
