### ISSUE TITLE
Handling Game Errors in the Container

### ISSUE THREAD

**Issue by jamieowen** [SpringRoll/SpringRoll#66]
Hey Matt,

Apologies for the stream of issues! I'm in the process of introducing the new Container into the PBS Games App..

I'm using a lot of PBS Games being pulled from Springroll that are generating errors on IOS 9.
I had been using a custom Container previously and I was handling errors generated by the iframe container by adding a global error listener to the iframe.
```
// once iframe is loaded...
iframe.contentWindow.onerror = function(){
   // game generated an error.
}
```
I was wondering if this functionality could be added to either Bellhop or the new Springroll Container. This way we can 'close' a game gracefully if errors are found in the Game code..

Currently, when a game is generating errors ( and i just ignore them ) it seems to be killing reusing the container.
I try to wait for for a 'closed' event to be dispatched from the container before navigating away from the Container but this loop is broken when an error occurs..

May be adding 'localError' events would be cool as well as the 'remoteError' that exist already..

Cheers,

Jamie

**Comment by bigtimebuddy** [comment]
@jamieowen  I needed to handle this as a Bellhop event and couldn't use the `onerror` property of the contentWindow because of cross-domain restrictions. I took your suggestion and the Container also now dispatches a `localError` event. 

The downside of approach is that the games will need to be updated to the latest SpringRoll library in order to avoid the uncaught game errors messing up the Container process on the game-side. The change is available in releases SpringRoll 0.3.16 and 0.4.6.

**Comment by jamieowen** [comment]
Hey Matt,

That makes sense, I haven't had to deal with crossdomain so far as we download the archive zip and unpack and run locally on the device.

I did add the new Container from yesterday and one thing I did notice is that when some errors do occur in an iframe contentWindow, the Container resets, and the contentWindow is effectively killed - its methods/props are all null.  ( This may be when the src is set blank on the iframe ).  As the Bellhop instance stores its target reference to the contentWindow rather than the iframe, the subsequent postMessage calls fail.

I checked my old container, and realised that every time I loaded a new game into the same iframe I was destroying the previous Bellhop instance then instantiating a new one each time.  So I haven't seen these issues before.

I guess theres a few options - 
- I could create a new Container instance each time I load a new game,
- The Container is modified to create a new Bellhop instance each open call
- Or Bellhop is modified to handle the switch in contentWindow

Also, was your plan to add global error handling on the child Bellhop instance then communicate this back to the parent instance / Container? 

It seems like it would be useful especially as Apple love to fuck things up in future versions of Safari!

**Comment by bigtimebuddy** [comment]
@jamieowen A new Bellhop instance [is already created](https://github.com/SpringRoll/SpringRoll/blob/master/src/container/Container.js#L380) on every open call (either `openPath` or `openRemote`). Also, a `reset` happens when a crash occurs while attempting to destroy/close the game itself. 

I added global error handling to the game instance and this [bubbles up](https://github.com/SpringRoll/SpringRoll/blob/master/src/container/ContainerPlugin.js#L150-L160) to the Container via a `localError` event with Bellhop. 

Can you explain more the error that you are getting? When is the game crash happening?

**Comment by jamieowen** [comment]
@bigtimebuddy Ok, i missed that with Bellhop creation.

That narrows it down then.. 

Firstly my close process is - check Container if its loading or loaded, if it is, I call Container.close and wait for closed event.  If it isn't i just navigate away.

Ok so the first situation is with airshow. Basically the game loads first time - works ok.
When I close it, it generates an error.  The local error is dispatched but the Container.reset() method is setting the paused getter/setter which then triggers client send events. The contentWindow by this time has been killed. ( on iOS 9 )

![airshow-firstrun-onclose](https://cloud.githubusercontent.com/assets/248957/10944004/f0e32880-830e-11e5-9c08-4520f8861ddd.png)

Reopening the same game causes the same postMessage issues on openPath, so it doesn't begin to load game again :

![airshow-secondrun-onopen](https://cloud.githubusercontent.com/assets/248957/10944005/f0e4c4ce-830e-11e5-94a3-8871628cee45.png)

So for airshow it looks like we need some checks on the client to make sure the contentWindow/client is still good.

The second one is with chicken blast off.  On the first run ( after restarting the app ), the game generates an error immediately BUT localError is not called.  I close the game and navigate away.

![chickblast-firstrun-onopen](https://cloud.githubusercontent.com/assets/248957/10944006/f0e4c834-830e-11e5-8a4b-ceb235b282aa.png)

When i reopen the same game the Container is left in a state where it just emits a closed event straight away when openPath is called again. Which my UI just picks up on and navigates away.  Although I just thought, I could probably fix this one by resetting the Container each time.  
But either way the localError doesn't seem to pick up those errors.

![chickblast-secondrun-onopen](https://cloud.githubusercontent.com/assets/248957/10944007/f0e5e20a-830e-11e5-974d-5ad2ab6a425d.png)

**Comment by bigtimebuddy** [comment]
@jamieowen I worked on a [new version of Bellhop](https://github.com/SpringRoll/Bellhop/tree/dev) this morning that doesn't cache a reference the `contentWindow`, but instead just keeps a reference to the iframe. This might help from sending events after the contentWindow has been destroyed by iOS9. Do you think you could pull in this version of Bellhop (**dev** branch) and see if it helps this situation?

**Comment by jamieowen** [comment]
@bigtimebuddy The Bellhop fix works for the first issue.  Cheers!

For the other issue, I have manually set container.loading = false, before I call openPath for now.
When an error occurs before load is done, it obviously leaves the Container in a loading state without calling localError.
So it triggers the closed event straight away when i call openPath next time round..

**Comment by bigtimebuddy** [comment]
@jamieowen This is helpful. I don't know if there's anything we can do if an error happens _before_ the game's Bellhop instance is initialized. I image these are dependency issues, which happen before the SpringRoll Application is created. Obviously, the games _should_ get fixed to address these crashes and in a live production we wouldn't be deploying games that crash immediate on start-up.

**Comment by jamieowen** [comment]
@bigtimebuddy Yes makes sense, thats cool then, we can leave that out. 

Cheers for your help on this!

**Comment by jamieowen** [comment]
@bigtimebuddy I think the target fix on bellhop isn't working across all browsers.
Sometimes window.parent can be null, when i tested in Chrome.

As a quick solution I modified to this :

```
	Object.defineProperty(p, "target",
	{
		get: function()
		{
			var target = this.isChild ? window.parent : this.iframe.contentWindow;
			if( !target ){
				if( !this._fakeTarget ){
					this._fakeTarget = {
						postMessage:function(){}
					}
				}
				target = this._fakeTarget;
			}
			return target;
		}
	});

```

Although it would probably be cleaner to check if the target is not null before dispatching postMessage.

**Comment by bigtimebuddy** [comment]
Do you know why `window.parent` is null sometimes?

**Comment by jamieowen** [comment]
@bigtimebuddy I'm not too sure at the moment, as I haven't got much time to dig deeper.  But it seems to vary depending on browser and the change takes place when an error is thrown by the game.

**Comment by bigtimebuddy** [comment]
Okay. I made a [small change](https://github.com/SpringRoll/SpringRoll/commit/c1ef1708b46fb775f5071a2be93a28728ebc899f) to the Container class where the Bellhop instance is now destroyed whenever the container is reset (or closed). This destroying happens and stop those error from sending, for instance, pause events to a Bellhop instance that is toast.
