### ISSUE TITLE
Phaser.io Can't access Input Events

### ISSUE THREAD

**Issue by wgbh-dbiron** [SpringRoll/SpringRoll#67]
I'm using the Phaser template. I tried to just add a sprite and handle an onClick event and Drag event. I’m unable to click/drag the image as expected. 

...
// Library depencencies
	var Application = include('springroll.Application'),
		Game = include('Phaser.Game'),
		Phaser = include('Phaser');

	// Create a new application
	var app = new Application({
		name: "springroll_phaser_test",
		configPath: "assets/config/config.json"
	});

	// The Phaser game
	var game;

	// Handle when app is ready to use
	app.on('init', function()
	{
		// Start application
		this.game = game = new Game(
			980,
			640,
			Phaser.AUTO,
			"content",
			{
				preload: preload,
				create: create
			}
		);
	});

	// Preload assets for Phaser
	function preload()
	{
		game.load.image('logo', 'assets/images/logo.png');
	}

	// When the Phaser game has been created
	function create()
	{
		var logo = game.add.sprite(
			game.world.centerX, 
			game.world.centerY, 
			'logo'
		);
		logo.anchor.setTo(0.5, 0.5);
		logo.inputEnabled = true;
		logo.useHandCursor = true;
		logo.events.onInputDown.add(function(){
			console.log("Clicked here");
		});	
	}
...

This code works without SpringRoll. The Phaser Input Manager is somehow prevented from working as expected.

**Comment by bigtimebuddy** [comment]
See response in #68
