### ISSUE TITLE
Phaser.io Can't create Phaser.Button

### ISSUE THREAD

**Issue by wgbh-dbiron** [SpringRoll/SpringRoll#68]
Using Phaser template to create the project. I am unable to create a simple button. A weird error comes up - "Uncaught TypeError: Cannot read property 'start' of null”. The reference of the Input Manager is somehow being lost/null.

...
// Library depencencies
	var Application = include('springroll.Application'),
		Game = include('Phaser.Game'),
		Phaser = include('Phaser');

	// Create a new application
	var app = new Application({
		name: "springroll_phaser_test",
		configPath: "assets/config/config.json"
	});

	// The Phaser game
	var game;

	// Handle when app is ready to use
	app.on('init', function()
	{
		// Start application
		this.game = game = new Game(
			980,
			640,
			Phaser.AUTO,
			"content",
			{
				preload: preload,
				create: create
			}
		);
	});

	// Preload assets for Phaser
	function preload()
	{
		game.load.atlasXML('button_spritesheet', 'assets/images/spritesheet/button_spritesheet.png', 'assets/images/spritesheet/button_spritesheet.xml');
	}

	// When the Phaser game has been created
	function create()
	{	
		/// error occurs within the call here.
		var playButton = this.game.add.button(300, 300, 'button_spritesheet',
			onCloseDisplay, this, 'play_button_down', 'play_button_up', 'play_button_down');	
	}

	function onCloseDisplay()
	{
		console.log("Clicked onCloseDisplay");
	}
...

**Comment by bigtimebuddy** [comment]
Right now, we are not officially supporting Phaser and don't have immediate plans to more tightly integrate the two. We created a Template as a test but have not made significant efforts to have Phaser and SpringRoll play well together for a production usage. If you're planning on using Phaser, you'll probably need to do some work to make this happen.
