### ISSUE TITLE
Adding mousemove event to panel | Springroll

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#7]
I was trying to add mousemove event to panel, Event was not triggering.

this.panel.addEventListener("mousemove", function (evt) {
		    alert("hi");
});

**Comment by andrewstart** [comment]
EaselJS doesn't provide a mousemove event, but mouseover, mouseout, and pressmove: http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#event_pressmove
