### ISSUE TITLE
Loading transistion assets 

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#70]
I have tried the below option to load. Assets are loaded but its not reflecting in the transition.

ex: 
```
    var app = new Application({
        fps: 24,
        name: 'makebelieve',
        state: 'title',
        canvasId: 'stage',
        configPath: 'assets/config/config.json',
        manifestsPath: 'assets/config/manifests.json',
        captionsPath: 'assets/config/captions.json',
        display: Display,
        displayOptions: {
            clearView: true,
        },
        preload:
             [		
{ src: "assets/images/star1shape__daniel_outroALT.png", id:"star1shape__daniel_outroALT1" },
{ src: "assets/images/star2shape_daniel_outroALT.png", id: "star2shape_daniel_outroALT1" }
             ]
    });

  app.on('init', function () {
        this.options.transition = new transLib.Transition();

});
```
Only the graphics part is working,but images are not loading.

Please suggest some options to load assets for the transition.
Note : I am using 0.4 version springroll.

**Comment by praveen4565** [comment]
Can anyone give suggestion for the above?

**Comment by praveen4565** [comment]
Hi i tried another approach.. It worked..
But let me know is this right way to do it.


As the images get cached when we load it in application level. I have done some changes in Transition.js below are the code.


 (transLib.star1shape__daniel_outroALT = function () {
        this.initialize(app.getCache("star1shape__daniel_outroALT1"));
    }).prototype = p = new Bitmap();
    p.nominalBounds = new Rectangle(0, 0, 270, 270);


    (transLib.star2shape_daniel_outroALT = function () {
        this.initialize(app.getCache("star2shape_daniel_outroALT1"));
    }).prototype = p = new Bitmap();
    p.nominalBounds = new Rectangle(0, 0, 488, 488);

At the time of bitmap image initialization I have added the app.getCache("star2shape_daniel_outroALT1") than 
this.initialize(img.star2shape_daniel_outroALT1);

Its working for me as i expected. Could anyone can comment on this?

**Comment by bigtimebuddy** [comment]
Try something like this. You add a complete callback to each asset and add the resulting image to the global images object that CreateJS uses.

```
var app = new Application({
	fps: 24,
	name: 'makebelieve',
	state: 'title',
	canvasId: 'stage',
	configPath: 'assets/config/config.json',
	manifestsPath: 'assets/config/manifests.json',
	captionsPath: 'assets/config/captions.json',
	display: Display,
	displayOptions: {
		clearView: true,
	},
	preload:[{ 
		src: "assets/images/star1shape__daniel_outroALT.png", 
		id:"star1shape__daniel_outroALT1",
		complete: onImageLoaded               
	},{ 
		src: "assets/images/star2shape_daniel_outroALT.png", 
		id: "star2shape_daniel_outroALT1",
		complete: onImageLoaded
	}]
});

function onImageLoaded(img, asset)
{
	window.images[asset.id] = img;
}

app.on('init', function()
{
	this.options.transition = new transLib.Transition();
});
```

**Comment by praveen4565** [comment]
@bigtimebuddy  Thanks for the suggestion.
