### ISSUE TITLE
`autoPause: false` option doesn't work for Container blur events.

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#71]
Setting the `autoPause: false` option on an app doesn't work for Container blur events: these still pause the app. Is this intentional? If so, is there a way to prevent Container blur events from pausing the app?

**Comment by bigtimebuddy** [comment]
Auto pause was really only intended if the game ran in standalone mode. If the game is run in a container, the auto pausing is owned by the container's focus and blur.  Can you describe the case and why you need to ignore container blur events? Why is that functionality desirable?

**Comment by probityrules** [comment]
I was mostly confused about the "autoPause" behavior since I was getting sporadic behavior once the app was within a container: it might be helpful to note this somewhere.

My use case was mostly related to debugging, since pausing tends to get in the way and I was just wanting to turn it off :-)

**Comment by bigtimebuddy** [comment]
@probityrules cool. I'll add a property to the Container to completely turn off the browser-window auto pausing. I could see that be useful for debugging and potentially an app deployment.

**Comment by yanshcherbakovatredspace** [comment]
@probityrules Would this help your use case? #117

**Comment by probityrules** [comment]
Yes, I think this would work for me. It might be convenient to have the `disablePause` property set via app options similar to `autoPause` and `cacheBust` since it applies to the entire app's behavior, but regardless I believe the behavior itself should address my debugging case.

**Comment by yanshcherbakovatredspace** [comment]
This issue is addressed in the container and springroll library in https://github.com/SpringRoll/SpringRoll/pull/117 and https://github.com/SpringRoll/SpringRollContainer/pull/5

Currently in master.

Usage: Add `disablePause` as an application option and the pause event will not fire.
