### ISSUE TITLE
A `version` property in app options causes audio to fail.

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#72]
When I create an app with a `version` option having period separators (such as "1.2.3"), audio no longer plays. It appears that appending "?v=1.2.3" to audio files causes the Spring Roll version of SoundJS to not load the audio file.

It appears that in [`_parsePath`](https://github.com/SpringRoll/SoundJS/blob/master/src/soundjs/Sound.js#L1113), the path name is being split by the last version period separator instead of the path name period separator. If the filename is `sound.ogg?v=1.2.3`, this function declares the extension to be "3" instead of "ogg".

**Comment by bigtimebuddy** [comment]
Yeah, this is a known issue but we haven't gotten around to fixing it yet. The workaround is to not use periods in the version number, e.g. `1,2,3`.

**Comment by andrewstart** [comment]
The reason this bug exists is that we changed the path parsing in our fork of PreloadJS because we had a client using a service based CDN, using a url like `http://website.com/service/?asset=HFq25GK/assets/sounds/sound.ogg`.

**Comment by bigtimebuddy** [comment]
That CDN URL format is pretty non-conventional. In most cases, I think a URL proxy is a better structure for requesting files on a CDN. I think we use this more-standard implementation with the ability to override the parsing (in the case of the clients @andrewstart mentioned).

**Comment by probityrules** [comment]
Maybe you could update the regex to support both? Something like this:

    a = new RegExp(/^(?:(\w+:)\/{2}(\w+(?:\.\w+)*\/?))?([\/.]*?(?:[^?]+)?\/)?(?:((?:[^\/?]+)\.(\w+))(?:\?(\S+)?)?|(?:\S*\?\S+\.(\w+)))$/)
    
    a.exec('http://website.com/service/?asset=HFq25GK/assets/sounds/sound.ogg')
    // returns ["http://website.com/service/?asset=HFq25GK/assets/sounds/sound.ogg", "http:", "website.com/", "service/", undefined, undefined, undefined, "ogg"]
    
    a.exec('http://website.com/service/HFq25GK/assets/sounds/sound.ogg')
    // returns ["http://website.com/service/HFq25GK/assets/sounds/sound.ogg", "http:", "website.com/", "service/HFq25GK/assets/sounds/", "sound.ogg", "ogg", undefined, undefined]
    
    a.exec('http://website.com/service/HFq25GK/assets/sounds/sound.ogg?v=1.1.1')
    // returns ["http://website.com/service/HFq25GK/assets/sounds/sound.ogg?v=1.1.1", "http:", "website.com/", "service/HFq25GK/assets/sounds/", "sound.ogg", "ogg", "v=1.1.1", undefined]

**Comment by probityrules** [comment]
I would be happy to push a fix for this if we can pin down a solution. From what I can tell, there are two potential options:

1. Revert to SoundJS's original behavior, and specific games needing alternate behavior can specify a unique `createjs.Sound.FILE_PATTERN` to match their CDN asset format or inject an alternate `_parsePath` handler.
2. Update the current behavior to work with the CDN in the manner @andrewstart mentions as well as for versioned audio files (maybe using something like the regex's I listed above or adding an extra conditional check to the modified `_parsePath` code).

Let me know what you think; thanks!

**Comment by yanshcherbakovatredspace** [comment]
I'm on the fence between solution 1 and 2 that you suggest. Reverting SoundJS original behaviour might cause unforeseen issues if it's rolled out. Solution 2 seems the safer and more durable route, but I agree with @bigtimebuddy that a better structure would be a URL proxy for non-standard URL patterns.

**Comment by probityrules** [comment]
Considering @yanshcherbakovatredspace's comment, I put together a more robust version of @andrewstart's original allowance for query-string file names. Essentially, the updated method tries SoundJS's original behavior first, and then looks into the query string if the file path cannot resolve into a valid file format.

There's a bit more detail on [the pull request](https://github.com/SpringRoll/SoundJS/pull/1).

**Comment by yanshcherbakovatredspace** [comment]
@probityrules Good stuff! Just noted a few minor things in the pull request.

**Comment by probityrules** [comment]
I just verified that the updated _parsePath behavior resolves the original audio issue I reported, so I'm closing this; thanks!
