### ISSUE TITLE
pause / volume buttons in disable mode | springroll preview

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#74]
1) I have observed that pause / volume buttons in disable mode 

![error](https://cloud.githubusercontent.com/assets/13066894/11684494/e6e7a62c-9e97-11e5-99b3-8dd58324fa30.PNG)

2) As per the documentation app.paused will return true or false based on the application status.
     app.paused is returning false even when the application is paused

springroll version specified in the bower.json is : "~0.4"

**Comment by bigtimebuddy** [comment]
Please report this bug to [SpringRoll Studio](https://github.com/SpringRoll/SpringRoll).

**Comment by praveen4565** [comment]
Ok i will post the 1st point to springroll studio.

Why app.paused returning false even when the application get paused? is this springroll studio issue?
