### ISSUE TITLE
app.paused returning false when application pause

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#75]
i am using springroll version is : "~0.4".

I have checked by pausing the application, but app.paused returning false.

**Comment by bigtimebuddy** [comment]
This is the correct behavior. `app.paused` is the manual Application pause. If the Container pauses the Application, `app.paused` isn't changed to match.

**Comment by praveen4565** [comment]
How can I know that the application is paused or not programmatically?

**Comment by bigtimebuddy** [comment]
By listening to the [`pause`](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#event_pause), [`paused`](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#event_paused), and [`resumed`](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#event_resumed) events on the application.

```js
app.on('resumed', function(){
    // application is resumed from pause
});
```

**Comment by praveen4565** [comment]
Tried this, but am getting error in the console:

 app.on("paused", function () {
        console.log("test");
        app.paused = true;
    });

    app.on("resumed", function () {
        console.log("test1");
        app.paused = false;
    });


![erroronpause](https://cloud.githubusercontent.com/assets/13066894/11773404/4be871c2-a24f-11e5-8420-918e42a1160c.PNG)

**Comment by bigtimebuddy** [comment]
Setting `app.paused` on those even handlers will create a recursive loop (since the pause has already ben set), so you shouldn't do that. What are you trying to accomplish with regards to pausing? The Application should automatically handle pausing of any animation, audio, rendering and anything attached to SpringRoll's setTimeout.

**Comment by praveen4565** [comment]
As I am using Ticker to move object to different co ordinates. If application gets pause ticker will be running and the object not resumed where it was when the application get paused. To avoid this i was using app.paused to pause the ticker till the application gets into resumed state

**Comment by bigtimebuddy** [comment]
You should use Application's [`update`](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#event_update) event instead of using CreateJS's Ticker. The update event happens every frame just like Ticker but it automatically hooks into the Application pause state without any other work.

**Comment by praveen4565** [comment]
can i use multiple update event in a single class?

**Comment by bigtimebuddy** [comment]
Yup, you can create multiple update handlers.

**Comment by praveen4565** [comment]
is it possible to give an example on using multiple update in a single class?

**Comment by bigtimebuddy** [comment]
It's recommended to not use Ticker because, as you've found, there's a lot of extra work required to making sure the Ticker respects the pause state of the application. The solution here is to use the Application's update events. 

```js
// first update handler
function onUpdate1(elapsed)
{
    // elapsed is the time in milliseconds since the last update
    // "this" in this context is the app
}
// second update handler
function onUpdate2(elapsed)
{
    // elapsed is the time in milliseconds since the last update
    // "this" in this context is the app
}
app.on('update', onUpdate1);
app.on('update', onUpdate2);
```

**Comment by praveen4565** [comment]
If i want to stop anyone of the handler? app.off("update",onUpdate1); ? is this a right syntax?

**Comment by bigtimebuddy** [comment]
@praveen4565 yes, that's correct.

**Comment by praveen4565** [comment]
I tried by the approach u said, please find the below code

I have a functionality where it depends on the current frame number I have to trigger some events.
p.someFunction=function(){
 if (_panel.currentEnv === app.enviormentSetup.WATER) {
                    app.on("update", onUpdate.bind(this));
                }
}

function onUpdate() {
        if (this.currentObj.currentFrame % 2 !== 0) {
            this.generateBubble(100);
        }

        if (this.currentObj.currentFrame >= count) {
            console.log("test");
            app.off("update", onUpdate);
        }

    }


I tried the above example "on" is working fine but not "off"

**Comment by praveen4565** [comment]
Able to resolve. Working fine.. while triggering update function i had given bind(this) to function
