### ISSUE TITLE
need suggession

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#77]
I have a panel variable which holds a movieclip. I am using same variable for adding moveiclip to stage.
/*in panel*/
     this.danielObject = new lib.Daniel_SUPER_walks();
                this.danielObject.x = 254;
                this.danielObject.y = 360;
                this.danielObject.stop();
                this.addChild(this.danielObject);
                this.danielObject.head.mouth.gotoAndStop(5);
                app.animator.play(this.danielObject, { anim: "Daniel_SUPER_walks" }, function () {
                            this.bubbleAnim();
                }.bind(this));

p.bubbleAnim=function(){
}; 

After adding multiple animations to stage using same variable. callback function of animator called the times i used the this.danielObject to add movieclip to stage. Even tried making null to remove the reference of variable

**Comment by andrewstart** [comment]
If you are removing this.danielObject before the animation completes, then you need to call `app.animator.stop(this.danielObject);` to stop the animation and cancel the animation complete callback.

**Comment by praveen4565** [comment]
@andrewstart  thanks it worked....
