### ISSUE TITLE
Upgrading springroll from version 0.3 to 0.4

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#78]
I would like to get advice on upgrading a sprinigroll project from 0.3 to 0.4. Does upgrade process affect the project significantly?  

Reason to upgrade - Wanted to show the asset loading progress(in %) on the the screen and I understand that this feature is available from 0.4  version.

**Comment by andrewstart** [comment]
The release notes for the 0.4.x releases should have better specifics, but the major changes that I can think of right now are:

* PBS modules (tracking) are moved to separate libraries in repos hosted by them. 
* Loading is done with Application.instance.load(), and all States support a list of assets to load and unload automatically when entering and exiting.
* easeljs BaseState callbacks, like onAssetsLoaded, have beenreplaced with the events that all states use. 
* springroll.easeljs.Animator has been replaced with a property on the Application -  use Application.instance.animator,which requires the new animation module.

**Comment by yanshcherbakovatredspace** [comment]
This should probably be moved to the wiki section.

**Comment by yanshcherbakovatredspace** [comment]
Will create a section in the wiki.
