### ISSUE TITLE
Breaking the assets js into multiple js

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#80]
We have around 82 js files which has been generated from various  fla files, and after minification(build), assets.js reaches nearly 6mb. This causes high loading time at the initial launch of game. Is there any option which helps to break down the assets js into multiple js and load them in background.

We tried adding reference n springroll.json as 

"assets": [
		"assets/fla/js/*.js"
	],
	"main": [
		"src/*.js"
	], 
"assets2":[
"some js reference"
]

we expected the assets2.js in the deploy/js folder but it wasn't. Is there any way to generate new js file? by referring in springrol.json?

**Comment by andrewstart** [comment]
```
"assets":{
    "initAssets":[
        "assets/fla/js/item1.js",
        "assets/fla/js/item2.js"
    ],
    "otherAssets":[
        "assets/fla/js/item3.js",
        "assets/fla/js/item4.js"
    ]
},
"main": [
    "src/*.js"
]```

Where 'initAssets' and 'otherAssets' are names you choose and can be as many or as few as you want.

**Comment by praveen4565** [comment]
@andrewstart  Thanks..
