### ISSUE TITLE
Merge multiple config sources...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRoll#81]
Is there a way to choose multiple sources to create the SpringRoll config file? I tried turning springroll.json's config property into an Array, but springroll-grunt doesn't like that.

If not, I think this might be a useful feature. For example, we have generated configuration files that should be included in the final deploy config, but having generated content in our src/config folder alongside original content can get confusing.

**Comment by andrewstart** [comment]
This definitely would be a useful feature to have (make an issue on the [grunt-springroll repo](https://github.com/SpringRoll/grunt-springroll). In the time being, you could override the concat-json task to add other subtasks for different output files. In `<project>/tasks/overrides` add a `concat-json.js` file that looks something like 
```
module.exports = {
	release: {
		base: "<%= build.config %>",
		src: "<%= build.config %>/**/*.{json,js}",
		dest: "<%= configFile %>"
	},
	debug: {
		base: "<%= build.config %>",
		src: "<%= build.config %>/**/*.{json,js}",
		dest: "<%= configFile %>",
		options: {
			space: "\t"
		}
	}
};
```
where 'release' and 'debug' are replaced by your own names. Then just run `grunt concat-json:mySubTask` to build that config file.

**Comment by probityrules** [comment]
Thanks Andrew, this is helpful.

I originally tried, but it looks like issues are not enabled on that repo.

**Comment by andrewstart** [comment]
Huh, that's interesting. I enabled issues and made an issue for this.

**Comment by probityrules** [comment]
On further investigation, I think I may be able to accomplish what I need using JavaScript files inside the config folder that export dynamically-created JSON. I am actually trying to take multiple source paths and putting them into a single game config, not trying to create multiple configs from multiple sources (although I imagine that might be useful for other use-cases).
