### ISSUE TITLE
On every tap on stage the game is getting paused - project created using Default template

### ISSUE THREAD

**Issue by chetansind** [SpringRoll/SpringRoll#84]
I have created a project using the Default template by selecting the below modules 
- Debug
- Sound
- Native Display
- Keyboard

On every tap on stage, the game gets grayed out and paused. We have to tap it again to resume the game. 
Please suggest.

I have added the project here [DefaultGame](http://cst-ts.excelindia.com/DefaultGame/)

**Comment by chetansind** [comment]
Please suggest.
Thanks

**Comment by andrewstart** [comment]
In Chrome on Windows or Android, I'm not seeing what you are describing.

**Comment by chetansind** [comment]
Please find the video of the issue
[Video](https://youtu.be/iCguiJtR2hg)

**Comment by andrewstart** [comment]
I would imagine that it would be an issue with whatever container you have set up - perhaps @bigtimebuddy would have some ideas.

**Comment by bigtimebuddy** [comment]
@chetansind Does this happen when previewing other games in SpringRoll Studio?

**Comment by chetansind** [comment]
@bigtimebuddy It happens when the projects created using default template (with the selected modules listed above).

I tried creating project by choosing Container Client and Native Display and it is working fine now. 
Thanks.

**Comment by andrewstart** [comment]
The problem was by leaving out the Container Client module - it is required to communicate with the Container to decide when the game/window has actually lost focus, and when you have only changed focus between iframe and parent window.
