### ISSUE TITLE
Cannot build with pixi

### ISSUE THREAD

**Issue by xoorath** [SpringRoll/SpringRoll#86]
Hey,

when trying to install we cannot build the libraries, and when concat:libraries gets to pixi, it freaks out about a base64 string it's expecting inside of a path. Windows has a hard time moving around our project folder as well because it seems to think this file really exists and its path is way too long.

Here's the huge text.
```
[4mRunning "concat:libraries" (concat) task[24m
[31m>> [39mSource file "components/springroll-pbskids/dist/modules/google-analytics.js" not found.
[33mWarning: Unable to read "C:\Program Files (x86)\Jenkins\jobs\ourgame\workspace\components\pixi.js\bin\data:application\json;charset:utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCJub2RlX21vZHVsZXMvYXN5bmMvbGliL2FzeW5jLmpzIiwibm9kZV9tb2R1bGVzL2Jyb3dzZXJpZnkvbm9kZV9tb2R1bGVzL3BhdGgtYnJvd3NlcmlmeS9pbmRleC5qcyIsIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9wcm9jZXNzL2Jyb3dzZXIuanMiLCJub2RlX21vZHVsZXMvYnJvd3NlcmlmeS9ub2RlX21vZHVsZXMvcHVueWNvZGUvcHVueWNvZGUuanMiLCJub2RlX21vZHVsZXMvYnJvd3NlcmlmeS9ub2RlX21vZHVsZXMvcXVlcnlzdHJpbmctZXMzL2RlY29kZS5qcyIsIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdW


<omitting like 100k lines of base64 text>


AgfTtcbn1cblxuaWYgKCFnbG9iYWwuY2FuY2VsQW5pbWF0aW9uRnJhbWUpIHtcbiAgICBnbG9iYWwuY2FuY2VsQW5pbWF0aW9uRnJhbWUgPSBmdW5jdGlvbihpZCkge1xuICAgICAgICBjbGVhclRpbWVvdXQoaWQpO1xuICAgIH07XG59XG4iXX0=" file (Error code: ENAMETOOLONG). Use --force to continue.[39m
```

**Comment by bigtimebuddy** [comment]
Looks like the latest version of SpringRoll's Pixi.js fork was built with base64 maps turned on. Workaround in the meantime by changing **springroll.json**'s reference to "pixi.js" and changing to  "pixi.min.js" (minified version doesn't have the source maps).

**Comment by bigtimebuddy** [comment]
I reported the issue on [pixi.js](https://github.com/pixijs/pixi.js/issues/2317).

**Comment by xoorath** [comment]
The workaround seems to fine for us to use for now. Thanks for following up on this so quickly! :rainbow:

**Comment by yanshcherbakovatredspace** [comment]
I've encountered this same issue and found that this is due to a [bug in grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat/issues/144) which is solved by the pull request to grunt-contrib-concat module [#130](https://github.com/gruntjs/grunt-contrib-concat/pull/130) which was merged and released in version [grunt-contrib-concat v0.5.1](https://github.com/gruntjs/grunt-contrib-concat/releases/tag/v0.5.1)

The way I've gone around this issue is simply bump the version from 0.5.0 to 0.5.1 in grunt-springroll.

**Comment by rckincade** [comment]
@xoorath - If you're satisfied with either resolution to this issue, please update the status of the bug, and close it. Once you've done that, we can do the same in our internal issue tracking. Thank you!

**Comment by yanshcherbakovatredspace** [comment]
Closing this issue as a workaround and fix has been provided.
