### ISSUE TITLE
springroll.Positioner class | clarification

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#9]
When i was reading springroll API, I found Positioner class. Will it helps to find object collision? Please share if any example? What exactly hitArea?

**Comment by bigtimebuddy** [comment]
`springroll.Positioner` is an internally class used by the `springroll.ScaleManager`. In the next version of the docs, we'll be excluding private classes. SpringRoll does not have any object collision detection system, however we added some additional features to our fork of EaselJS (see [notes here](https://github.com/SpringRoll/EaselJS#springroll-specific-changes)). In particular we added `hitShape` which allows you to hit test a point against any object (Ellipse, Circle, Polygon, etc) on a `createjs.DisplayObject`--as opposed to the just the `hitArea` Rectangle built-in EaselJS.

```js
var clip = new createjs.MovieClip();
clip.hitShape = new createjs.Circle(10, 10, 20); // x, y, radius
clip.hitTest(10, 10); // x, y ... returns true
```

**Comment by praveen4565** [comment]
How can we use image rather shapes(circle,Rectangle. etc..)? To detect hitTest between two images?

**Comment by bigtimebuddy** [comment]
Currently in EaselJS (and in our fork) you can only `hitTest` a point (x, y) against an object or that object's `hitArea` or `hitShape`. There's not shape-to-shape hit detection in EaselJS.

**Comment by theBarge** [comment]
There are existing open-source projects that seem to do what you are trying
to accomplish. We haven't implemented it, but
https://github.com/olsn/Collision-Detection-for-EaselJS seems to be what
you are looking for.
