### ISSUE TITLE
vo complete callback wont trigger on continues tap | Android

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#90]
I found an behavior while an audio is playing at the same time if we continue sly tap on the stage the complete callback of audio which is already playing doesn't trigger. Once we stop the tapping on stage callback will trigger. I have disabled  the mouse event for all the objects on stage except background image to avoid slowness in the low power devices.

**Comment by andrewstart** [comment]
If you include in the Application options when initializing the game `raf:false`, the update loop won't be as smooth as it will be using setTimeout() instead of requestAnimationFrame(), but the update loop won't block other events.

**Comment by bigtimebuddy** [comment]
See #8

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
