### ISSUE TITLE
Optimization information

### ISSUE THREAD

**Issue by andrewstart** [SpringRoll/SpringRoll#91]
The wiki needs a page on optimization for CreateJS and Pixi.

**Comment by andrewstart** [comment]
The page has been created, with the major bits about art: https://github.com/SpringRoll/SpringRoll/wiki/Optimized-Art-Creation-and-Usage

**Comment by yanshcherbakovatredspace** [comment]
Will expand on this doc.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
