### ISSUE TITLE
 A problem occurred with this webpage so it was reloaded. | IOS Devices

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#94]
Am facing problem in Iphone 4S(iOS 8.0.3) and ipadmini (iOS 9.2.1).After playing game sometime, application getting reloded by throwing Error message "A problem occurred with this webpage so it was reloaded." Is there any specific reason to this? 

I am already managing memory by clearing the unallocated  variables to null.

**Comment by andrewstart** [comment]
This error generally happens when a page uses too much memory - perhaps you are trying to load up too much at once, or you need to make sure you are unloading and destroying assets and objects where possible, and nulling everything you can when you are finished with them.

**Comment by praveen4565** [comment]
Yep, I have a doubt. If we are overloading assets using app.load() in complete callback am adding the loaded images to images variable(window object). If we add images to window.images, will application itself handle unloading the images file?

**Comment by andrewstart** [comment]
If the Application isn't caching the images and didn't put the images in
window.images itself, it doesn't know to remove them.

**Comment by praveen4565** [comment]
@andrewstart , We have option to preload assets when state gets trigger. for Example

this.states = {
		title: new SomeState(
previous: 'title',
			next: 'title',
			preload: fla.somefile  [Assume here we trying to preload assets generated from fla file]
)
		game: getGameState()
	};	

preload will load all the assets and add to images variable at the time of onComplete callback of eacj asset(images). And if I navigate from one state to another, we cannot find images of both the state in images variable. We can only find current state images. This is what I understood.

If above case is true, images downloaded to browser and un used images should be unloaded using app.unload() method?

**Comment by andrewstart** [comment]
The application unloads those assets when you leave the state. I had
thought you were adding other asset loads outside of the state asset
loading feature.

**Comment by praveen4565** [comment]
Yes , I am loading few assets after states loads using app.load()(images and few js files). As per your suggestion, I should unload the assets am loading using app.load(). right?

**Comment by andrewstart** [comment]
Yes, however you need to make sure that you are telling the app to cache
the assets, otherwise app.unload() won't do anything.

**Comment by praveen4565** [comment]
@andrewstart  Thanks. How to make images to cache? any sample example for it? It would be more helpful.

**Comment by andrewstart** [comment]
As shown in the docs(
http://springroll.io/SpringRoll/docs/classes/springroll.Application.html#method_load)
, you can have a cache property on your load object or you can pass true as
the 4th parameter to load()

**Comment by praveen4565** [comment]
@andrewstart , thanks. I am loading few js files dynamically, can I make it unloaded after utilizing the js?

**Comment by andrewstart** [comment]
Yes, the [wiki has an example of loading a springroll.easeljs.FlashArt](https://github.com/SpringRoll/SpringRoll/wiki/Loading-Assets#flash-art-task), which handles proper unloading of javascript animation files.

**Comment by praveen4565** [comment]
@andrewstart , As per the documentation mentioned in the above comment. We have to load the js file  like 

app.load({
    src: "assets/js/Transition.js",
    type: "easeljs",
    format: "springroll.easeljs.FlashArt"
}) 



if we want to unload the js file? 

app.unload('Transition') is this enough?

**Comment by andrewstart** [comment]
Almost - you need to make sure the load is getting cached, which can be done by adding a cache property to the load object:
```javascript
app.load({
    id:"Transition",
    src: "assets/js/Transition.js",
    type: "easeljs",
    format: "springroll.easeljs.FlashArt",
    cache: true
}) 
```

**Comment by praveen4565** [comment]
Thanks, I have another doubt. 

this.states = {
title: new SomeState(
previous: 'title',
next: 'title',
preload: fla.somefile [Assume here we trying to preload assets generated from fla file]
)
game: getGameState()
}; 
Images which is preloaded using "preload" option ? will that be cached? unloading of images done by the framework or we have to manually say unload?

**Comment by andrewstart** [comment]
Any asset in a state's preload array is cached when it is loaded, and is unloaded when you leave the state. Additionally, when your state extends `springroll.easeljs.BaseState`, that is what automatically adds those loaded images to `window.images`.

**Comment by praveen4565** [comment]
@andrewstart , Is adding and removing movie clip continuously,  will that make performance issue? do you have any idea on this?.
Today when I was running the application in ipadmini (iOS 9.2.1) , In my application continuously 3 to 4 heavy animation movie clips will run at a time, from my findings for sure multiple animation run will affect the fps rate to degrade. At the lower time if we try to add or remove the movie clip from stage application might crash right? I would like to know your thoughts on this.

**Comment by andrewstart** [comment]
Adding and removing things will have a small performance hit of function calls and event dispatching, so if you are doing it a lot, it would be much faster to stop animation on that clip and toggle its visibility instead of removing it. If you have movie clips that you know are slow to render, try some of the recommendations in https://github.com/SpringRoll/SpringRoll/wiki/Optimized-Art-Creation-and-Usage to optimize them.

**Comment by yanshcherbakovatredspace** [comment]
Closing this issue as a recommendation has been provided.
