### ISSUE TITLE
TypeError : null is not an object (evaluating 'clip.framerate')

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#96]
Am facing this issue in the lower power devices (Samsung Galaxy Tab 3(Android 4.4.2), iPad 4(iOS 8), iPhone 6(iOS 8) And iPhone 4s(iOS 8)). Can anyone help me out to resolve this issue?

![error](https://cloud.githubusercontent.com/assets/13066894/13777564/f1618682-ead6-11e5-9c1f-23fa3c1a081d.png)

It shows that there is some null reference in continer-client.js(line number 298).

**Comment by andrewstart** [comment]
The movieclip you are passing to `animator.play()` is null.

**Comment by yanshcherbakovatredspace** [comment]
@praveen4565 have you been able to resolve this issue?

**Comment by yanshcherbakovatredspace** [comment]
Closed. Response provided.
