### ISSUE TITLE
Kindle Fire HD 7 | Music keep playing for few seconds after minimizing the browser

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#97]
When the background music is playing, then we minimize the browser audio keeps playing for few seconds and then it pause in Kindle Fire HD 7 device.

Please suggest.

**Comment by andrewstart** [comment]
This sounds like a limitation of the browser/device - the focus loss/blur event from the browser is delayed in making it to SpringRoll, so it is not able to pause audio immediately.

**Comment by yanshcherbakovatredspace** [comment]
Will verify if this is a limitation of the Kindle.

**Comment by yanshcherbakovatredspace** [comment]
This is verified, it's not limited to background music. All sounds keep playing for up to 2 seconds after the Silk browser is minimized.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
