### ISSUE TITLE
Internet Explorer 10 & 11 audio hitches and delays

### ISSUE THREAD

**Issue by mkucic** [SpringRoll/SpringRoll#98]
I've been getting some audio hitches and delays in Internet Explorer 10 and 11 when playing audio files for the first time. 
It appears that the Flash Player fallback system is the culprit as Edge and other browsers that implement WebAudio do not have the same issue.

**Comment by probityrules** [comment]
We have experienced similar issues in our games. It seems to be a browser limitation as noted here: http://createjs.com/docs/soundjs/classes/FlashAudioPlugin.html

> There can be a delay in flash player starting playback of audio. This has been most noticeable in Firefox. Unfortunely this is an issue with the flash player and the browser and therefore cannot be addressed by SoundJS.

**Comment by andrewstart** [comment]
Yeah, Internet Explorer tends to be bad, with slower JS performance (and no WebGL for 9/10) and the Flash fallback for audio, which tend to result in problems across the board.

**Comment by yanshcherbakovatredspace** [comment]
Closing as this is a limitation of Internet Explorer
