### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by xoorath** [SpringRoll/SpringRoll#99]
In the example [http://springroll.io/SpringRoll/examples/sound.html](http://springroll.io/SpringRoll/examples/sound.html) it doesn't appear any audio is playing. On each button press the console will log an error for each sound: `Play failed for sound 'FoodChute'`

The stack:

`
debug.js:794 Play failed for sound 'TipEarned'Debug.error @ debug.js:794p._playAfterLoad @ sound.js:1428p._markLoaded @ sound.js:1924p.taskDone @ core.js:6131(anonymous function) @ core.js:4719p._onComplete @ core.js:5255p._onCompleted @ core.js:5012b._dispatchEvent @ preloadjs.min.js:12b.dispatchEvent @ preloadjs.min.js:12b._sendFileComplete @ preloadjs.min.js:13b._processFinishedLoad @ preloadjs.min.js:13b._handleFileComplete @ preloadjs.min.js:13(anonymous function) @ preloadjs.min.js:12b._dispatchEvent @ preloadjs.min.js:12b.dispatchEvent @ preloadjs.min.js:12b._sendComplete @ preloadjs.min.js:12b.handleEvent @ preloadjs.min.js:12(anonymous function) @ preloadjs.min.js:12b._dispatchEvent @ preloadjs.min.js:12b.dispatchEvent @ preloadjs.min.js:12b._handleLoad @ preloadjs.min.js:12b._handleReadyStateChange @ preloadjs.min.js:12(anonymous function) @ preloadjs.min.js:12
`

Running google chrome Version 49.0.2623.112m on Windows 7.

**Comment by andrewstart** [comment]
I log that error if the sound I tried to play with SoundJS failed to play (`state == 'playFailed'`). Is there any reason to believe that this could be an issue on your hardware, like a lack of available audio channels or audio hardware (as far as Chrome is concerned, at least)?

**Comment by xoorath** [comment]
I'm able to run just about any other html5 game with sound I could think of running quickly. (just tried phaser).

If you have a test you would like me to visit and try, I can do that.

**Comment by ericente** [comment]
It's not working in Firefox either, but FF logs a 404 on the file load in
the console. In the network panel, it looks like the audio is loading fine.

**Comment by andrewstart** [comment]
Well, that took longer to figure out than it should have. Turns out our fork of PreloadJS is not in a working state, because I left it off updating from CreateJS's main version, but hadn't made a tag because I hadn't tested it yet. Unfortunately, Bower was just pulling in the master branch instead of the latest tag, and was grabbing a broken version.
